//! gm-store: SQLite persistence (rusqlite, bundled) + PGN import/export.
//!
//! * One `Mutex<Connection>` (WAL, foreign keys, busy timeout) shared by cheap `Store` clones.
//! * Schema migrations tracked with `PRAGMA user_version`; every migration is idempotent.
//! * All SQL is parameterized and goes through the (bounded) prepared-statement cache.
//! * User input is validated and size-capped; nothing on an input path panics.

use std::path::Path;
use std::sync::Arc;

use anyhow::{anyhow, bail, Context};
use parking_lot::Mutex;
use rusqlite::{params, Connection, OptionalExtension, Row, ToSql};
use serde::{Deserialize, Serialize};

pub mod activity;
pub mod adaptive;
pub mod backup;
pub mod classics;
pub mod drills;
pub mod pgn;
pub mod rating;
pub mod repertoire;
pub mod srs;
pub mod training;
pub mod weekly;

pub use pgn::ParsedGame;

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct GameRecord {
    pub id: i64,
    pub white: String,
    pub black: String,
    /// "1-0" | "0-1" | "1/2-1/2" | "*"
    pub result: String,
    pub termination: String,
    pub start_fen: String,
    /// UCI
    pub moves: Vec<String>,
    pub pgn: String,
    pub bot_id: Option<String>,
    pub user_color: Option<String>,
    pub time_control: Option<String>,
    pub opening_name: Option<String>,
    pub accuracy_white: Option<f32>,
    pub accuracy_black: Option<f32>,
    pub review_json: Option<String>,
    pub notes: String,
    pub tags: Vec<String>,
    pub favorite: bool,
    pub created_at: String,
    pub updated_at: String,
}

/// All `GameRecord` fields except pgn, moves, review_json; plus `move_count`.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct GameSummary {
    pub id: i64,
    pub white: String,
    pub black: String,
    pub result: String,
    pub termination: String,
    pub start_fen: String,
    pub bot_id: Option<String>,
    pub user_color: Option<String>,
    pub time_control: Option<String>,
    pub opening_name: Option<String>,
    pub accuracy_white: Option<f32>,
    pub accuracy_black: Option<f32>,
    pub notes: String,
    pub tags: Vec<String>,
    pub favorite: bool,
    pub created_at: String,
    pub updated_at: String,
    pub move_count: u32,
}

/// pgn is generated by the store.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct NewGame {
    pub white: String,
    pub black: String,
    pub result: String,
    pub termination: String,
    pub start_fen: String,
    pub moves: Vec<String>,
    pub bot_id: Option<String>,
    pub user_color: Option<String>,
    pub time_control: Option<String>,
    pub opening_name: Option<String>,
    pub notes: String,
    pub tags: Vec<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct GameQuery {
    pub search: Option<String>,
    pub result: Option<String>,
    pub bot_id: Option<String>,
    pub favorite: Option<bool>,
    pub limit: Option<u32>,
    pub offset: Option<u32>,
}

/// Every field optional: only provided fields are changed.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct GamePatch {
    pub notes: Option<String>,
    pub tags: Option<Vec<String>>,
    pub favorite: Option<bool>,
    pub result: Option<String>,
    pub termination: Option<String>,
    pub moves: Option<Vec<String>>,
    pub review_json: Option<String>,
    pub accuracy_white: Option<f32>,
    pub accuracy_black: Option<f32>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct Profile {
    pub name: String,
    pub avatar: String,
    pub puzzle_rating: f32,
    pub puzzle_rd: f32,
    pub rush_best: u32,
    pub puzzles_solved: u32,
    pub puzzles_failed: u32,
    pub streak_days: u32,
    pub last_active: String,
    pub settings_json: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct ProfilePatch {
    pub name: Option<String>,
    pub avatar: Option<String>,
    pub settings_json: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct PuzzleResult {
    pub rating: f32,
    pub delta: f32,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct LessonProgress {
    pub course_id: String,
    pub lesson_id: String,
    pub completed: bool,
    pub updated_at: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct BotRecord {
    pub bot_id: String,
    pub played: u32,
    pub won: u32,
    pub lost: u32,
    pub drawn: u32,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct RatingPoint {
    /// ISO-8601 timestamp
    pub at: String,
    pub rating: f32,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct Stats {
    /// Games the user played inside the app (games with a `user_color`).
    pub games_played: u32,
    pub games_won: u32,
    pub games_lost: u32,
    pub games_drawn: u32,
    /// Every saved game, including imported ones.
    pub total_games: u32,
    /// Percentage 0..100 of decided+drawn games won (None when no finished games).
    pub win_rate: Option<f32>,
    /// Per-bot record, most played first.
    pub per_bot: Vec<BotRecord>,
    /// Average accuracy of the user's side over reviewed games.
    pub avg_accuracy: Option<f32>,
    /// Puzzle rating history, oldest first (last 100 points).
    pub rating_history: Vec<RatingPoint>,
    /// Most recent played games, newest first (up to 10).
    pub recent_results: Vec<RecentResult>,
    pub puzzle_rating: f32,
    pub puzzle_rd: f32,
    pub puzzles_solved: u32,
    pub puzzles_failed: u32,
    pub rush_best: u32,
    pub streak_days: u32,
    pub lessons_completed: u32,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct RecentResult {
    pub id: i64,
    pub opponent: String,
    pub bot_id: Option<String>,
    pub user_color: Option<String>,
    /// PGN result string
    pub result: String,
    /// "win" | "loss" | "draw" | "unfinished" from the user's point of view
    pub outcome: String,
    pub accuracy: Option<f32>,
    pub opening_name: Option<String>,
    pub created_at: String,
}

/// SQLite store. Cheap to clone (shared connection behind a mutex).
#[derive(Clone)]
pub struct Store {
    conn: Arc<Mutex<Connection>>,
}

impl std::fmt::Debug for Store {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Store")
    }
}

// ---------------------------------------------------------------------------------------------
// Limits
// ---------------------------------------------------------------------------------------------

const MAX_NAME: usize = 100;
const MAX_TERMINATION: usize = 100;
const MAX_SHORT: usize = 100;
const MAX_NOTES: usize = 20_000;
const MAX_TAGS: usize = 20;
const MAX_TAG_LEN: usize = 32;
const MAX_REVIEW_BYTES: usize = 8 * 1024 * 1024;
const MAX_SETTINGS_BYTES: usize = 64 * 1024;
const MAX_IMPORT_GAMES: usize = 2000;
const DEFAULT_LIMIT: u32 = 50;
const MAX_LIMIT: u32 = 500;
const STMT_CACHE: usize = 64;
/// Keep at most this many rows in append-only history tables.
const HISTORY_KEEP: i64 = 20_000;

const NOW: &str = "strftime('%Y-%m-%dT%H:%M:%SZ','now')";

// ---------------------------------------------------------------------------------------------
// Migrations
// ---------------------------------------------------------------------------------------------

type Migration = fn(&rusqlite::Transaction<'_>) -> rusqlite::Result<()>;

/// Index i migrates user_version i -> i+1. Append only; never edit a shipped migration.
const MIGRATIONS: &[Migration] = &[migrate_v1, migrate_v2, migrate_v3];

fn has_column(tx: &rusqlite::Transaction<'_>, table: &str, col: &str) -> rusqlite::Result<bool> {
    let mut stmt = tx.prepare("SELECT 1 FROM pragma_table_info(?1) WHERE name = ?2")?;
    stmt.exists(params![table, col])
}

fn migrate_v1(tx: &rusqlite::Transaction<'_>) -> rusqlite::Result<()> {
    tx.execute_batch(
        r#"
CREATE TABLE IF NOT EXISTS games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  white TEXT NOT NULL DEFAULT '', black TEXT NOT NULL DEFAULT '',
  result TEXT NOT NULL DEFAULT '*', termination TEXT NOT NULL DEFAULT '',
  start_fen TEXT NOT NULL DEFAULT '', moves TEXT NOT NULL DEFAULT '', pgn TEXT NOT NULL DEFAULT '',
  bot_id TEXT, user_color TEXT, time_control TEXT, opening_name TEXT,
  accuracy_white REAL, accuracy_black REAL, review_json TEXT,
  notes TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL DEFAULT '', favorite INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);
CREATE TABLE IF NOT EXISTS profile (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  name TEXT NOT NULL DEFAULT 'Player',
  avatar TEXT NOT NULL DEFAULT '♟️',
  puzzle_rating REAL NOT NULL DEFAULT 1200,
  puzzle_rd REAL NOT NULL DEFAULT 350,
  rush_best INTEGER NOT NULL DEFAULT 0,
  puzzles_solved INTEGER NOT NULL DEFAULT 0,
  puzzles_failed INTEGER NOT NULL DEFAULT 0,
  streak_days INTEGER NOT NULL DEFAULT 0,
  last_active TEXT NOT NULL DEFAULT '',
  settings_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);
INSERT OR IGNORE INTO profile (id) VALUES (1);
CREATE TABLE IF NOT EXISTS puzzle_attempts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  puzzle_id TEXT NOT NULL,
  puzzle_rating INTEGER NOT NULL,
  solved INTEGER NOT NULL,
  time_ms INTEGER NOT NULL DEFAULT 0,
  rating_before REAL NOT NULL,
  rating_after REAL NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);
CREATE INDEX IF NOT EXISTS idx_puzzle_attempts_puzzle ON puzzle_attempts(puzzle_id);
CREATE TABLE IF NOT EXISTS rating_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kind TEXT NOT NULL DEFAULT 'puzzle',
  attempt_id INTEGER REFERENCES puzzle_attempts(id) ON DELETE CASCADE,
  rating REAL NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);
CREATE INDEX IF NOT EXISTS idx_rating_history_kind ON rating_history(kind, id);
CREATE TABLE IF NOT EXISTS rush_scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  score INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);
CREATE TABLE IF NOT EXISTS lesson_progress (
  course_id TEXT NOT NULL,
  lesson_id TEXT NOT NULL,
  completed INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
  PRIMARY KEY (course_id, lesson_id)
) WITHOUT ROWID;
"#,
    )?;
    // A pre-migration scaffold may have created `games` without these columns.
    if !has_column(tx, "games", "headers_json")? {
        tx.execute_batch("ALTER TABLE games ADD COLUMN headers_json TEXT NOT NULL DEFAULT '[]'")?;
    }
    if !has_column(tx, "games", "move_count")? {
        tx.execute_batch("ALTER TABLE games ADD COLUMN move_count INTEGER NOT NULL DEFAULT 0")?;
        tx.execute_batch(
            "UPDATE games SET move_count = CASE WHEN moves = '' THEN 0 \
             ELSE length(moves) - length(replace(moves, ' ', '')) + 1 END",
        )?;
    }
    tx.execute_batch(
        r#"
CREATE INDEX IF NOT EXISTS idx_games_created ON games(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_games_bot ON games(bot_id);
CREATE INDEX IF NOT EXISTS idx_games_favorite ON games(favorite);
"#,
    )?;
    Ok(())
}

/// v2: learning-platform features. Each feature module owns its own tables.
fn migrate_v2(tx: &rusqlite::Transaction<'_>) -> rusqlite::Result<()> {
    activity::schema(tx)?;
    adaptive::schema(tx)?;
    backup::schema(tx)?;
    classics::schema(tx)?;
    drills::schema(tx)?;
    repertoire::schema(tx)?;
    srs::schema(tx)?;
    training::schema(tx)?;
    Ok(())
}

/// v3: coaching, practice and home-use features. Each feature module owns its own tables;
/// add one `<module>::schema(tx)?;` line per module (keep them sorted).
fn migrate_v3(tx: &rusqlite::Transaction<'_>) -> rusqlite::Result<()> {
    let _ = tx;
    weekly::schema(tx)?;
    Ok(())
}

fn migrate(conn: &mut Connection) -> anyhow::Result<()> {
    let current: i64 = conn.query_row("PRAGMA user_version", [], |r| r.get(0))?;
    let target = MIGRATIONS.len() as i64;
    if current > target {
        bail!("database schema version {current} is newer than this build supports ({target})");
    }
    for (i, m) in MIGRATIONS.iter().enumerate().skip(current.max(0) as usize) {
        let tx = conn.transaction()?;
        m(&tx).with_context(|| format!("migration to schema v{}", i + 1))?;
        // PRAGMA cannot be parameterized; the value is a trusted integer.
        tx.execute_batch(&format!("PRAGMA user_version = {}", i + 1))?;
        tx.commit()?;
    }
    Ok(())
}

fn configure(conn: &Connection, wal: bool) -> anyhow::Result<()> {
    conn.busy_timeout(std::time::Duration::from_secs(5))?;
    if wal {
        let mode: String =
            conn.pragma_update_and_check(None, "journal_mode", "WAL", |r| r.get(0))?;
        if !mode.eq_ignore_ascii_case("wal") {
            tracing::warn!("SQLite WAL mode unavailable (journal_mode = {mode})");
        }
        conn.pragma_update(None, "synchronous", "NORMAL")?;
    }
    conn.pragma_update(None, "foreign_keys", "ON")?;
    conn.pragma_update(None, "temp_store", "MEMORY")?;
    // Bounded page cache (~8 MiB).
    conn.pragma_update(None, "cache_size", -8000)?;
    conn.set_prepared_statement_cache_capacity(STMT_CACHE);
    Ok(())
}

// ---------------------------------------------------------------------------------------------
// Input helpers
// ---------------------------------------------------------------------------------------------

/// Trim, drop control characters (except newlines/tabs when `multiline`) and cap length (chars).
fn clean_text(s: &str, max_chars: usize, multiline: bool) -> String {
    s.trim()
        .chars()
        .filter(|c| !c.is_control() || (multiline && (*c == '\n' || *c == '\t')))
        .take(max_chars)
        .collect::<String>()
        .trim_end()
        .to_string()
}

fn clean_opt(s: &Option<String>, max: usize) -> Option<String> {
    s.as_deref()
        .map(|v| clean_text(v, max, false))
        .filter(|v| !v.is_empty())
}

fn clean_tags(tags: &[String]) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for t in tags {
        let t = clean_text(t, MAX_TAG_LEN, false);
        if !t.is_empty() && !out.iter().any(|o| o.eq_ignore_ascii_case(&t)) {
            out.push(t);
            if out.len() >= MAX_TAGS {
                break;
            }
        }
    }
    out
}

fn clean_color(c: &Option<String>) -> Option<String> {
    match c.as_deref().map(|s| s.trim().to_ascii_lowercase()) {
        Some(s) if s == "white" || s == "w" => Some("white".into()),
        Some(s) if s == "black" || s == "b" => Some("black".into()),
        _ => None,
    }
}

fn clean_accuracy(a: Option<f32>) -> Option<f32> {
    a.filter(|v| v.is_finite()).map(|v| v.clamp(0.0, 100.0))
}

/// Validates and canonicalizes a start FEN + UCI move list.
fn validate_game(start_fen: &str, moves: &[String]) -> anyhow::Result<(String, Vec<String>)> {
    if moves.len() > pgn::MAX_PLIES {
        bail!("too many moves (max {})", pgn::MAX_PLIES);
    }
    let fen = pgn::canonical_fen(start_fen).map_err(|e| anyhow!("invalid start position: {e}"))?;
    let moves: Vec<String> = moves
        .iter()
        .map(|m| m.trim().to_ascii_lowercase())
        .collect();
    pgn::uci_to_sans(&fen, &moves).map_err(|e| anyhow!("invalid move list: {e}"))?;
    Ok((fen, moves))
}

fn tags_to_db(tags: &[String]) -> String {
    serde_json::to_string(tags).unwrap_or_else(|_| "[]".into())
}

fn tags_from_db(s: &str) -> Vec<String> {
    let s = s.trim();
    if s.is_empty() {
        return Vec::new();
    }
    serde_json::from_str::<Vec<String>>(s).unwrap_or_else(|_| {
        s.split(',')
            .map(|t| t.trim().to_string())
            .filter(|t| !t.is_empty())
            .collect()
    })
}

fn moves_from_db(s: &str) -> Vec<String> {
    s.split_whitespace().map(str::to_string).collect()
}

fn headers_from_db(s: &str) -> Vec<(String, String)> {
    serde_json::from_str(s).unwrap_or_default()
}

fn set_header(headers: &mut Vec<(String, String)>, name: &str, value: Option<&str>) {
    let idx = headers
        .iter()
        .position(|(k, _)| k.eq_ignore_ascii_case(name));
    match (idx, value.filter(|v| !v.is_empty())) {
        (Some(i), Some(v)) => headers[i].1 = v.to_string(),
        (None, Some(v)) => headers.push((name.to_string(), v.to_string())),
        (Some(i), None) => {
            headers.remove(i);
        }
        (None, None) => {}
    }
}

/// "win" | "loss" | "draw" | "unfinished" from the user's perspective.
fn outcome_for(user_color: Option<&str>, result: &str) -> &'static str {
    match (user_color, result) {
        (_, "1/2-1/2") => "draw",
        (Some("white"), "1-0") | (Some("black"), "0-1") => "win",
        (Some("white"), "0-1") | (Some("black"), "1-0") => "loss",
        _ => "unfinished",
    }
}

fn round1(v: f64) -> f32 {
    ((v * 10.0).round() / 10.0) as f32
}

// ---------------------------------------------------------------------------------------------
// Row mapping
// ---------------------------------------------------------------------------------------------

const GAME_COLS: &str = "id, white, black, result, termination, start_fen, moves, pgn, bot_id, \
    user_color, time_control, opening_name, accuracy_white, accuracy_black, review_json, notes, \
    tags, favorite, created_at, updated_at";

const SUMMARY_COLS: &str = "id, white, black, result, termination, start_fen, bot_id, user_color, \
    time_control, opening_name, accuracy_white, accuracy_black, notes, tags, favorite, created_at, \
    updated_at, move_count";

fn row_to_game(r: &Row<'_>) -> rusqlite::Result<GameRecord> {
    Ok(GameRecord {
        id: r.get(0)?,
        white: r.get(1)?,
        black: r.get(2)?,
        result: r.get(3)?,
        termination: r.get(4)?,
        start_fen: r.get(5)?,
        moves: moves_from_db(&r.get::<_, String>(6)?),
        pgn: r.get(7)?,
        bot_id: r.get(8)?,
        user_color: r.get(9)?,
        time_control: r.get(10)?,
        opening_name: r.get(11)?,
        accuracy_white: r.get::<_, Option<f64>>(12)?.map(|v| v as f32),
        accuracy_black: r.get::<_, Option<f64>>(13)?.map(|v| v as f32),
        review_json: r.get(14)?,
        notes: r.get(15)?,
        tags: tags_from_db(&r.get::<_, String>(16)?),
        favorite: r.get::<_, i64>(17)? != 0,
        created_at: r.get(18)?,
        updated_at: r.get(19)?,
    })
}

fn row_to_summary(r: &Row<'_>) -> rusqlite::Result<GameSummary> {
    Ok(GameSummary {
        id: r.get(0)?,
        white: r.get(1)?,
        black: r.get(2)?,
        result: r.get(3)?,
        termination: r.get(4)?,
        start_fen: r.get(5)?,
        bot_id: r.get(6)?,
        user_color: r.get(7)?,
        time_control: r.get(8)?,
        opening_name: r.get(9)?,
        accuracy_white: r.get::<_, Option<f64>>(10)?.map(|v| v as f32),
        accuracy_black: r.get::<_, Option<f64>>(11)?.map(|v| v as f32),
        notes: r.get(12)?,
        tags: tags_from_db(&r.get::<_, String>(13)?),
        favorite: r.get::<_, i64>(14)? != 0,
        created_at: r.get(15)?,
        updated_at: r.get(16)?,
        move_count: r.get::<_, i64>(17)?.clamp(0, u32::MAX as i64) as u32,
    })
}

fn get_game_in(conn: &Connection, id: i64) -> anyhow::Result<Option<GameRecord>> {
    let mut stmt = conn.prepare_cached(&format!("SELECT {GAME_COLS} FROM games WHERE id = ?1"))?;
    Ok(stmt.query_row([id], row_to_game).optional()?)
}

fn get_headers_in(conn: &Connection, id: i64) -> anyhow::Result<Vec<(String, String)>> {
    let mut stmt = conn.prepare_cached("SELECT headers_json FROM games WHERE id = ?1")?;
    let s: Option<String> = stmt.query_row([id], |r| r.get(0)).optional()?;
    Ok(s.map(|s| headers_from_db(&s)).unwrap_or_default())
}

/// Insert a fully validated game. Returns the new id.
fn insert_game(
    conn: &Connection,
    g: &NewGame,
    start_fen: &str,
    moves: &[String],
    headers: &[(String, String)],
) -> anyhow::Result<i64> {
    let result = pgn::normalize_result(&g.result);
    let pgn_text = pgn::to_pgn(headers, start_fen, moves, result);
    let mut stmt = conn.prepare_cached(
        "INSERT INTO games (white, black, result, termination, start_fen, moves, pgn, bot_id, \
         user_color, time_control, opening_name, notes, tags, favorite, headers_json, move_count) \
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, 0, ?14, ?15)",
    )?;
    stmt.execute(params![
        g.white,
        g.black,
        result,
        g.termination,
        start_fen,
        moves.join(" "),
        pgn_text,
        g.bot_id,
        g.user_color,
        g.time_control,
        g.opening_name,
        g.notes,
        tags_to_db(&g.tags),
        serde_json::to_string(headers).unwrap_or_else(|_| "[]".into()),
        moves.len() as i64,
    ])?;
    Ok(conn.last_insert_rowid())
}

/// Sanitize a `NewGame` in place (names, tags, lengths...).
fn clean_new_game(g: &NewGame) -> NewGame {
    let name = |s: &str, dflt: &str| {
        let c = clean_text(s, MAX_NAME, false);
        if c.is_empty() {
            dflt.to_string()
        } else {
            c
        }
    };
    NewGame {
        white: name(&g.white, "White"),
        black: name(&g.black, "Black"),
        result: pgn::normalize_result(&g.result).to_string(),
        termination: clean_text(&g.termination, MAX_TERMINATION, false),
        start_fen: g.start_fen.clone(),
        moves: g.moves.clone(),
        bot_id: clean_opt(&g.bot_id, MAX_SHORT),
        user_color: clean_color(&g.user_color),
        time_control: clean_opt(&g.time_control, MAX_SHORT),
        opening_name: clean_opt(&g.opening_name, MAX_NAME * 2),
        notes: clean_text(&g.notes, MAX_NOTES, true),
        tags: clean_tags(&g.tags),
    }
}

/// Bumps the daily streak (UTC days). Call inside the same lock as the activity.
/// The streak logic lives in [`activity`], the single source of truth.
fn touch_activity(conn: &Connection) -> anyhow::Result<()> {
    activity::touch_profile(conn)
}

fn prune(conn: &Connection, table: &'static str) -> anyhow::Result<()> {
    // `table` is a compile-time constant, never user input.
    conn.prepare_cached(&format!(
        "DELETE FROM {table} WHERE id <= (SELECT MAX(id) FROM {table}) - ?1"
    ))?
    .execute([HISTORY_KEEP])?;
    Ok(())
}

fn get_profile_in(conn: &Connection) -> anyhow::Result<Profile> {
    let mut stmt = conn.prepare_cached(
        "SELECT name, avatar, puzzle_rating, puzzle_rd, rush_best, puzzles_solved, puzzles_failed, \
         last_active, settings_json \
         FROM profile WHERE id = 1",
    )?;
    // Streak: computed from the activity log + profile run (see `activity::streak_in`).
    let streak = activity::streak_in(conn)?.current;
    let p = stmt.query_row([], |r| {
        Ok(Profile {
            name: r.get(0)?,
            avatar: r.get(1)?,
            puzzle_rating: r.get::<_, f64>(2)?.round() as f32,
            puzzle_rd: r.get::<_, f64>(3)?.round() as f32,
            rush_best: r.get::<_, i64>(4)?.clamp(0, u32::MAX as i64) as u32,
            puzzles_solved: r.get::<_, i64>(5)?.clamp(0, u32::MAX as i64) as u32,
            puzzles_failed: r.get::<_, i64>(6)?.clamp(0, u32::MAX as i64) as u32,
            // A streak is broken once a full day is missed.
            streak_days: streak,
            last_active: r.get(7)?,
            settings_json: r.get(8)?,
        })
    })?;
    Ok(p)
}

fn to_u32(v: i64) -> u32 {
    v.clamp(0, u32::MAX as i64) as u32
}

// ---------------------------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------------------------

impl Store {
    /// Opens (or creates) the database and runs migrations.
    pub fn open(path: &Path) -> anyhow::Result<Store> {
        if let Some(dir) = path.parent().filter(|d| !d.as_os_str().is_empty()) {
            std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
        }
        let mut conn = Connection::open(path)?;
        configure(&conn, true)?;
        migrate(&mut conn)?;
        Ok(Store {
            conn: Arc::new(Mutex::new(conn)),
        })
    }

    /// In-memory database (tests).
    pub fn open_in_memory() -> anyhow::Result<Store> {
        let mut conn = Connection::open_in_memory()?;
        configure(&conn, false)?;
        migrate(&mut conn)?;
        Ok(Store {
            conn: Arc::new(Mutex::new(conn)),
        })
    }

    // ----- games -----

    pub fn list_games(&self, q: &GameQuery) -> anyhow::Result<Vec<GameSummary>> {
        let mut sql = format!("SELECT {SUMMARY_COLS} FROM games WHERE 1=1");
        let mut args: Vec<Box<dyn ToSql>> = Vec::new();

        if let Some(search) = q
            .search
            .as_deref()
            .map(|s| clean_text(s, 100, false))
            .filter(|s| !s.is_empty())
        {
            let escaped = search
                .replace('\\', "\\\\")
                .replace('%', "\\%")
                .replace('_', "\\_");
            args.push(Box::new(format!("%{escaped}%")));
            let n = args.len();
            sql.push_str(&format!(
                " AND (white LIKE ?{n} ESCAPE '\\' OR black LIKE ?{n} ESCAPE '\\' \
                 OR opening_name LIKE ?{n} ESCAPE '\\' OR notes LIKE ?{n} ESCAPE '\\' \
                 OR tags LIKE ?{n} ESCAPE '\\' OR termination LIKE ?{n} ESCAPE '\\' \
                 OR bot_id LIKE ?{n} ESCAPE '\\')"
            ));
        }
        if let Some(result) = q
            .result
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty() && *s != "all")
        {
            match result.to_ascii_lowercase().as_str() {
                "win" | "won" | "wins" => sql.push_str(
                    " AND ((user_color = 'white' AND result = '1-0') OR (user_color = 'black' AND result = '0-1'))",
                ),
                "loss" | "lost" | "losses" => sql.push_str(
                    " AND ((user_color = 'white' AND result = '0-1') OR (user_color = 'black' AND result = '1-0'))",
                ),
                "draw" | "draws" => sql.push_str(" AND result = '1/2-1/2'"),
                "unfinished" | "ongoing" => sql.push_str(" AND result = '*'"),
                _ => {
                    args.push(Box::new(pgn::normalize_result(result).to_string()));
                    sql.push_str(&format!(" AND result = ?{}", args.len()));
                }
            }
        }
        if let Some(bot) = q.bot_id.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
            args.push(Box::new(bot.to_string()));
            sql.push_str(&format!(" AND bot_id = ?{}", args.len()));
        }
        if let Some(fav) = q.favorite {
            args.push(Box::new(fav as i64));
            sql.push_str(&format!(" AND favorite = ?{}", args.len()));
        }
        let limit = q.limit.unwrap_or(DEFAULT_LIMIT).clamp(1, MAX_LIMIT);
        let offset = q.offset.unwrap_or(0).min(10_000_000);
        args.push(Box::new(limit as i64));
        args.push(Box::new(offset as i64));
        sql.push_str(&format!(
            " ORDER BY created_at DESC, id DESC LIMIT ?{} OFFSET ?{}",
            args.len() - 1,
            args.len()
        ));

        let conn = self.conn.lock();
        let mut stmt = conn.prepare_cached(&sql)?;
        let refs: Vec<&dyn ToSql> = args.iter().map(|b| b.as_ref()).collect();
        let rows = stmt.query_map(refs.as_slice(), row_to_summary)?;
        Ok(rows.collect::<Result<Vec<_>, _>>()?)
    }

    pub fn get_game(&self, id: i64) -> anyhow::Result<Option<GameRecord>> {
        let conn = self.conn.lock();
        get_game_in(&conn, id)
    }

    /// The stored PGN tag pairs of a game (useful for re-export with original tags).
    pub fn get_game_headers(&self, id: i64) -> anyhow::Result<Vec<(String, String)>> {
        let conn = self.conn.lock();
        get_headers_in(&conn, id)
    }

    pub fn create_game(&self, g: &NewGame) -> anyhow::Result<GameRecord> {
        let g = clean_new_game(g);
        let (fen, moves) = validate_game(&g.start_fen, &g.moves)?;
        let conn = self.conn.lock();
        let date: String = conn
            .prepare_cached("SELECT strftime('%Y.%m.%d','now','localtime')")?
            .query_row([], |r| r.get(0))?;
        let mut headers: Vec<(String, String)> = vec![
            (
                "Event".into(),
                if g.bot_id.is_some() {
                    "GrandMentor vs Bot".into()
                } else {
                    "GrandMentor Game".into()
                },
            ),
            ("Site".into(), "GrandMentor".into()),
            ("Date".into(), date),
            ("Round".into(), "-".into()),
            ("White".into(), g.white.clone()),
            ("Black".into(), g.black.clone()),
            ("Result".into(), g.result.clone()),
        ];
        set_header(&mut headers, "TimeControl", g.time_control.as_deref());
        set_header(&mut headers, "Termination", Some(g.termination.as_str()));
        set_header(&mut headers, "Opening", g.opening_name.as_deref());
        let id = insert_game(&conn, &g, &fen, &moves, &headers)?;
        if g.user_color.is_some() {
            touch_activity(&conn)?;
        }
        get_game_in(&conn, id)?.ok_or_else(|| anyhow!("game {id} vanished after insert"))
    }

    pub fn update_game(&self, id: i64, patch: &GamePatch) -> anyhow::Result<Option<GameRecord>> {
        // Validate the expensive / fallible bits before taking the lock.
        if let Some(r) = &patch.review_json {
            if r.len() > MAX_REVIEW_BYTES {
                bail!("review too large");
            }
            serde_json::from_str::<serde::de::IgnoredAny>(r)
                .map_err(|e| anyhow!("review_json is not valid JSON: {e}"))?;
        }

        let conn = self.conn.lock();
        let Some(mut g) = get_game_in(&conn, id)? else {
            return Ok(None);
        };
        let mut regenerate = false;

        if let Some(moves) = &patch.moves {
            let (_, moves) = validate_game(&g.start_fen, moves)?;
            if moves != g.moves {
                g.moves = moves;
                regenerate = true;
            }
        }
        if let Some(r) = &patch.result {
            let r = pgn::normalize_result(r).to_string();
            if r != g.result {
                g.result = r;
                regenerate = true;
            }
        }
        if let Some(t) = &patch.termination {
            let t = clean_text(t, MAX_TERMINATION, false);
            if t != g.termination {
                g.termination = t;
                regenerate = true;
            }
        }
        if let Some(n) = &patch.notes {
            g.notes = clean_text(n, MAX_NOTES, true);
        }
        if let Some(t) = &patch.tags {
            g.tags = clean_tags(t);
        }
        if let Some(f) = patch.favorite {
            g.favorite = f;
        }
        if let Some(r) = &patch.review_json {
            g.review_json = Some(r.clone());
        }
        if patch.accuracy_white.is_some() {
            g.accuracy_white = clean_accuracy(patch.accuracy_white);
        }
        if patch.accuracy_black.is_some() {
            g.accuracy_black = clean_accuracy(patch.accuracy_black);
        }

        let mut headers = get_headers_in(&conn, id)?;
        if regenerate {
            if headers.is_empty() {
                headers = vec![
                    ("White".into(), g.white.clone()),
                    ("Black".into(), g.black.clone()),
                ];
            }
            set_header(&mut headers, "Result", Some(&g.result));
            set_header(&mut headers, "Termination", Some(&g.termination));
            g.pgn = pgn::to_pgn(&headers, &g.start_fen, &g.moves, &g.result);
        }

        conn.prepare_cached(&format!(
            "UPDATE games SET result = ?2, termination = ?3, moves = ?4, pgn = ?5, \
             accuracy_white = ?6, accuracy_black = ?7, review_json = ?8, notes = ?9, tags = ?10, \
             favorite = ?11, headers_json = ?12, move_count = ?13, updated_at = {NOW} WHERE id = ?1"
        ))?
        .execute(params![
            id,
            g.result,
            g.termination,
            g.moves.join(" "),
            g.pgn,
            g.accuracy_white.map(f64::from),
            g.accuracy_black.map(f64::from),
            g.review_json,
            g.notes,
            tags_to_db(&g.tags),
            g.favorite as i64,
            serde_json::to_string(&headers).unwrap_or_else(|_| "[]".into()),
            g.moves.len() as i64,
        ])?;
        get_game_in(&conn, id)
    }

    pub fn delete_game(&self, id: i64) -> anyhow::Result<bool> {
        let conn = self.conn.lock();
        let n = conn
            .prepare_cached("DELETE FROM games WHERE id = ?1")?
            .execute([id])?;
        Ok(n > 0)
    }

    /// Imports every game of a (multi-game) PGN atomically. Games with illegal moves are
    /// skipped when others parse; if none parse, the parse error is returned.
    pub fn import_pgn(&self, text: &str) -> anyhow::Result<Vec<GameRecord>> {
        self.import_pgn_with(text, |_, _| None)
    }

    /// Like [`Store::import_pgn`], but `name_opening(start_fen, uci_moves)` supplies an opening
    /// name for games whose PGN has no `Opening` tag.
    pub fn import_pgn_with(
        &self,
        text: &str,
        name_opening: impl Fn(&str, &[String]) -> Option<String>,
    ) -> anyhow::Result<Vec<GameRecord>> {
        let games = pgn::parse_pgn(text).map_err(|e| anyhow!("could not read PGN: {e}"))?;
        if games.len() > MAX_IMPORT_GAMES {
            bail!("too many games in one import (max {MAX_IMPORT_GAMES})");
        }
        let mut conn = self.conn.lock();
        let tx = conn.transaction()?;
        let mut ids = Vec::with_capacity(games.len());
        for pg in &games {
            let h = |k: &str| {
                pg.header(k)
                    .map(str::to_string)
                    .filter(|v| !v.is_empty() && v != "?")
            };
            let opening = h("Opening")
                .map(|o| match h("Variation") {
                    Some(v) => format!("{o}: {v}"),
                    None => o,
                })
                .or_else(|| name_opening(&pg.start_fen, &pg.moves));
            let ng = clean_new_game(&NewGame {
                white: h("White").unwrap_or_default(),
                black: h("Black").unwrap_or_default(),
                result: pg.result.clone(),
                termination: h("Termination").unwrap_or_default(),
                start_fen: pg.start_fen.clone(),
                moves: pg.moves.clone(),
                bot_id: None,
                user_color: None,
                time_control: h("TimeControl").filter(|t| t != "-"),
                opening_name: opening,
                notes: String::new(),
                tags: vec!["imported".into()],
            });
            let mut headers: Vec<(String, String)> = pg
                .headers
                .iter()
                .filter(|(k, _)| !k.eq_ignore_ascii_case("SetUp") && !k.eq_ignore_ascii_case("FEN"))
                .cloned()
                .collect();
            set_header(&mut headers, "Result", Some(&ng.result));
            ids.push(insert_game(&tx, &ng, &pg.start_fen, &pg.moves, &headers)?);
        }
        tx.commit()?;
        let mut out = Vec::with_capacity(ids.len());
        for id in ids {
            if let Some(g) = get_game_in(&conn, id)? {
                out.push(g);
            }
        }
        Ok(out)
    }

    /// Concatenated PGN of all games matching `q` (for "export library").
    pub fn export_pgn(&self, q: &GameQuery) -> anyhow::Result<String> {
        let ids: Vec<i64> = self.list_games(q)?.into_iter().map(|g| g.id).collect();
        let conn = self.conn.lock();
        let mut out = String::new();
        let mut stmt = conn.prepare_cached("SELECT pgn FROM games WHERE id = ?1")?;
        for id in ids {
            if let Some(p) = stmt.query_row([id], |r| r.get::<_, String>(0)).optional()? {
                out.push_str(p.trim_end());
                out.push_str("\n\n");
            }
        }
        Ok(out)
    }

    // ----- profile -----

    pub fn get_profile(&self) -> anyhow::Result<Profile> {
        let conn = self.conn.lock();
        get_profile_in(&conn)
    }

    pub fn update_profile(&self, p: &ProfilePatch) -> anyhow::Result<Profile> {
        if let Some(s) = &p.settings_json {
            if s.len() > MAX_SETTINGS_BYTES {
                bail!("settings too large");
            }
            let v: serde_json::Value = serde_json::from_str(s)
                .map_err(|e| anyhow!("settings_json is not valid JSON: {e}"))?;
            if !v.is_object() {
                bail!("settings_json must be a JSON object");
            }
        }
        let conn = self.conn.lock();
        if let Some(name) = &p.name {
            let name = clean_text(name, 40, false);
            if name.is_empty() {
                bail!("name cannot be empty");
            }
            conn.prepare_cached("UPDATE profile SET name = ?1 WHERE id = 1")?
                .execute([name])?;
        }
        if let Some(avatar) = &p.avatar {
            let avatar = clean_text(avatar, 16, false);
            if !avatar.is_empty() {
                conn.prepare_cached("UPDATE profile SET avatar = ?1 WHERE id = 1")?
                    .execute([avatar])?;
            }
        }
        if let Some(s) = &p.settings_json {
            conn.prepare_cached("UPDATE profile SET settings_json = ?1 WHERE id = 1")?
                .execute([s])?;
        }
        get_profile_in(&conn)
    }

    // ----- puzzles -----

    /// Rates a puzzle attempt (Glicko-2-lite) and returns the new rating and the change, both
    /// rounded to whole points as shown to the user.
    pub fn record_puzzle_attempt(
        &self,
        puzzle_id: &str,
        puzzle_rating: u16,
        solved: bool,
        time_ms: u64,
    ) -> anyhow::Result<PuzzleResult> {
        let puzzle_id = clean_text(puzzle_id, 64, false);
        if puzzle_id.is_empty() {
            bail!("puzzle id is required");
        }
        let time_ms = time_ms.min(24 * 3600 * 1000) as i64;
        let mut conn = self.conn.lock();
        let tx = conn.transaction()?;
        let (old_r, old_rd): (f64, f64) = tx
            .prepare_cached("SELECT puzzle_rating, puzzle_rd FROM profile WHERE id = 1")?
            .query_row([], |r| Ok((r.get(0)?, r.get(1)?)))?;
        let (new_r, new_rd) = rating::update(old_r, old_rd, f64::from(puzzle_rating), solved);
        tx.prepare_cached(
            "INSERT INTO puzzle_attempts (puzzle_id, puzzle_rating, solved, time_ms, rating_before, rating_after) \
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        )?
        .execute(params![puzzle_id, puzzle_rating, solved as i64, time_ms, old_r, new_r])?;
        let attempt_id = tx.last_insert_rowid();
        tx.prepare_cached(
            "INSERT INTO rating_history (kind, attempt_id, rating) VALUES ('puzzle', ?1, ?2)",
        )?
        .execute(params![attempt_id, new_r])?;
        tx.prepare_cached(
            "UPDATE profile SET puzzle_rating = ?1, puzzle_rd = ?2, \
             puzzles_solved = puzzles_solved + ?3, puzzles_failed = puzzles_failed + ?4 WHERE id = 1",
        )?
        .execute(params![new_r, new_rd, solved as i64, (!solved) as i64])?;
        touch_activity(&tx)?;
        prune(&tx, "rating_history")?;
        prune(&tx, "puzzle_attempts")?;
        tx.commit()?;
        let shown_new = new_r.round();
        Ok(PuzzleResult {
            rating: shown_new as f32,
            delta: (shown_new - old_r.round()) as f32,
        })
    }

    /// Records a Puzzle Rush score; returns the best score ever.
    pub fn record_rush(&self, score: u32) -> anyhow::Result<u32> {
        let score = score.min(10_000) as i64;
        let mut conn = self.conn.lock();
        let tx = conn.transaction()?;
        tx.prepare_cached("INSERT INTO rush_scores (score) VALUES (?1)")?
            .execute([score])?;
        tx.prepare_cached("UPDATE profile SET rush_best = MAX(rush_best, ?1) WHERE id = 1")?
            .execute([score])?;
        touch_activity(&tx)?;
        prune(&tx, "rush_scores")?;
        let best: i64 = tx
            .prepare_cached("SELECT rush_best FROM profile WHERE id = 1")?
            .query_row([], |r| r.get(0))?;
        tx.commit()?;
        Ok(to_u32(best))
    }

    // ----- lessons -----

    pub fn set_lesson_progress(
        &self,
        course_id: &str,
        lesson_id: &str,
        completed: bool,
    ) -> anyhow::Result<()> {
        let course_id = clean_text(course_id, 128, false);
        let lesson_id = clean_text(lesson_id, 128, false);
        if course_id.is_empty() || lesson_id.is_empty() {
            bail!("course_id and lesson_id are required");
        }
        let mut conn = self.conn.lock();
        let tx = conn.transaction()?;
        tx.prepare_cached(&format!(
            "INSERT INTO lesson_progress (course_id, lesson_id, completed, updated_at) VALUES (?1, ?2, ?3, {NOW}) \
             ON CONFLICT(course_id, lesson_id) DO UPDATE SET completed = excluded.completed, updated_at = excluded.updated_at"
        ))?
        .execute(params![course_id, lesson_id, completed as i64])?;
        if completed {
            touch_activity(&tx)?;
        }
        tx.commit()?;
        Ok(())
    }

    pub fn get_progress(&self) -> anyhow::Result<Vec<LessonProgress>> {
        let conn = self.conn.lock();
        let mut stmt = conn.prepare_cached(
            "SELECT course_id, lesson_id, completed, updated_at FROM lesson_progress \
             ORDER BY updated_at DESC, course_id, lesson_id LIMIT 10000",
        )?;
        let rows = stmt.query_map([], |r| {
            Ok(LessonProgress {
                course_id: r.get(0)?,
                lesson_id: r.get(1)?,
                completed: r.get::<_, i64>(2)? != 0,
                updated_at: r.get(3)?,
            })
        })?;
        Ok(rows.collect::<Result<Vec<_>, _>>()?)
    }

    // ----- stats -----

    pub fn stats(&self) -> anyhow::Result<Stats> {
        let conn = self.conn.lock();
        let mut s = Stats::default();

        let (played, won, lost, drawn, total): (i64, i64, i64, i64, i64) = conn
            .prepare_cached(
                "SELECT \
                   COALESCE(SUM(user_color IS NOT NULL), 0), \
                   COALESCE(SUM((user_color = 'white' AND result = '1-0') OR (user_color = 'black' AND result = '0-1')), 0), \
                   COALESCE(SUM((user_color = 'white' AND result = '0-1') OR (user_color = 'black' AND result = '1-0')), 0), \
                   COALESCE(SUM(user_color IS NOT NULL AND result = '1/2-1/2'), 0), \
                   COUNT(*) \
                 FROM games",
            )?
            .query_row([], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?, r.get(4)?)))?;
        s.games_played = to_u32(played);
        s.games_won = to_u32(won);
        s.games_lost = to_u32(lost);
        s.games_drawn = to_u32(drawn);
        s.total_games = to_u32(total);
        let finished = won + lost + drawn;
        s.win_rate = (finished > 0).then(|| round1(won as f64 * 100.0 / finished as f64));

        {
            let mut stmt = conn.prepare_cached(
                "SELECT bot_id, COUNT(*), \
                   SUM((user_color = 'white' AND result = '1-0') OR (user_color = 'black' AND result = '0-1')), \
                   SUM((user_color = 'white' AND result = '0-1') OR (user_color = 'black' AND result = '1-0')), \
                   SUM(result = '1/2-1/2') \
                 FROM games WHERE bot_id IS NOT NULL AND user_color IS NOT NULL \
                 GROUP BY bot_id ORDER BY COUNT(*) DESC, bot_id LIMIT 100",
            )?;
            let rows = stmt.query_map([], |r| {
                Ok(BotRecord {
                    bot_id: r.get(0)?,
                    played: to_u32(r.get(1)?),
                    won: to_u32(r.get::<_, Option<i64>>(2)?.unwrap_or(0)),
                    lost: to_u32(r.get::<_, Option<i64>>(3)?.unwrap_or(0)),
                    drawn: to_u32(r.get::<_, Option<i64>>(4)?.unwrap_or(0)),
                })
            })?;
            s.per_bot = rows.collect::<Result<Vec<_>, _>>()?;
        }

        let avg: Option<f64> = conn
            .prepare_cached(
                "SELECT AVG(CASE user_color WHEN 'white' THEN accuracy_white ELSE accuracy_black END) \
                 FROM games WHERE user_color IS NOT NULL \
                   AND (CASE user_color WHEN 'white' THEN accuracy_white ELSE accuracy_black END) IS NOT NULL",
            )?
            .query_row([], |r| r.get(0))?;
        s.avg_accuracy = avg.filter(|v| v.is_finite()).map(round1);

        {
            let mut stmt = conn.prepare_cached(
                "SELECT created_at, rating FROM (SELECT id, created_at, rating FROM rating_history \
                 WHERE kind = 'puzzle' ORDER BY id DESC LIMIT 100) ORDER BY id ASC",
            )?;
            let rows = stmt.query_map([], |r| {
                Ok(RatingPoint {
                    at: r.get(0)?,
                    rating: r.get::<_, f64>(1)?.round() as f32,
                })
            })?;
            s.rating_history = rows.collect::<Result<Vec<_>, _>>()?;
        }

        {
            let mut stmt = conn.prepare_cached(
                "SELECT id, white, black, bot_id, user_color, result, accuracy_white, accuracy_black, \
                   opening_name, created_at \
                 FROM games WHERE user_color IS NOT NULL ORDER BY created_at DESC, id DESC LIMIT 10",
            )?;
            let rows = stmt.query_map([], |r| {
                let white: String = r.get(1)?;
                let black: String = r.get(2)?;
                let color: Option<String> = r.get(4)?;
                let result: String = r.get(5)?;
                let (opponent, accuracy) = if color.as_deref() == Some("black") {
                    (white, r.get::<_, Option<f64>>(7)?)
                } else {
                    (black, r.get::<_, Option<f64>>(6)?)
                };
                Ok(RecentResult {
                    id: r.get(0)?,
                    opponent,
                    bot_id: r.get(3)?,
                    outcome: outcome_for(color.as_deref(), &result).to_string(),
                    user_color: color,
                    result,
                    accuracy: accuracy.map(|v| v as f32),
                    opening_name: r.get(8)?,
                    created_at: r.get(9)?,
                })
            })?;
            s.recent_results = rows.collect::<Result<Vec<_>, _>>()?;
        }

        let lessons: i64 = conn
            .prepare_cached("SELECT COUNT(*) FROM lesson_progress WHERE completed = 1")?
            .query_row([], |r| r.get(0))?;
        s.lessons_completed = to_u32(lessons);

        let p = get_profile_in(&conn)?;
        s.puzzle_rating = p.puzzle_rating;
        s.puzzle_rd = p.puzzle_rd;
        s.puzzles_solved = p.puzzles_solved;
        s.puzzles_failed = p.puzzles_failed;
        s.rush_best = p.rush_best;
        s.streak_days = p.streak_days;
        Ok(s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const OPERA: &str = r#"[Event "A Night at the Opera"]
[Site "Paris FRA"]
[Date "1858.??.??"]
[Round "?"]
[White "Paul Morphy"]
[Black "Duke Karl / Count Isouard"]
[Result "1-0"]
[Opening "Philidor Defense"]

1.e4 e5 2.Nf3 d6 3.d4 Bg4 4.dxe5 Bxf3 5.Qxf3 dxe5 6.Bc4 Nf6 7.Qb3 Qe7 8.Nc3 c6
9.Bg5 b5 10.Nxb5 cxb5 11.Bxb5+ Nbd7 12.O-O-O Rd8 13.Rxd7 Rxd7 14.Rd1 Qe6
15.Bxd7+ Nxd7 16.Qb8+ Nxb8 17.Rd8# 1-0
"#;

    fn sample(bot: &str, color: &str, result: &str) -> NewGame {
        NewGame {
            white: if color == "white" {
                "Me".into()
            } else {
                "Bot".into()
            },
            black: if color == "white" {
                "Bot".into()
            } else {
                "Me".into()
            },
            result: result.into(),
            termination: "checkmate".into(),
            start_fen: String::new(),
            moves: vec!["e2e4".into(), "e7e5".into(), "g1f3".into()],
            bot_id: Some(bot.into()),
            user_color: Some(color.into()),
            time_control: Some("600+5".into()),
            opening_name: Some("King's Knight Opening".into()),
            notes: "first game".into(),
            tags: vec!["fun".into(), "Fun".into(), " ".into()],
        }
    }

    #[test]
    fn opens() {
        Store::open_in_memory().unwrap();
    }

    #[test]
    fn crud() {
        let s = Store::open_in_memory().unwrap();
        let g = s.create_game(&sample("nelson", "white", "1-0")).unwrap();
        assert!(g.id > 0);
        assert_eq!(g.moves, vec!["e2e4", "e7e5", "g1f3"]);
        assert_eq!(g.tags, vec!["fun"]);
        assert_eq!(g.start_fen, pgn::START_FEN);
        assert!(g.pgn.contains("[White \"Me\"]"));
        assert!(g.pgn.contains("1. e4 e5 2. Nf3 1-0"));
        assert!(g.pgn.contains("[TimeControl \"600+5\"]"));

        let list = s.list_games(&GameQuery::default()).unwrap();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].move_count, 3);

        let up = s
            .update_game(
                g.id,
                &GamePatch {
                    notes: Some("great".into()),
                    favorite: Some(true),
                    moves: Some(vec![
                        "e2e4".into(),
                        "e7e5".into(),
                        "g1f3".into(),
                        "b8c6".into(),
                    ]),
                    result: Some("1/2-1/2".into()),
                    review_json: Some("{\"ok\":true}".into()),
                    accuracy_white: Some(87.5),
                    accuracy_black: Some(f32::NAN),
                    ..Default::default()
                },
            )
            .unwrap()
            .unwrap();
        assert_eq!(up.notes, "great");
        assert!(up.favorite);
        assert_eq!(up.moves.len(), 4);
        assert_eq!(up.result, "1/2-1/2");
        assert!(up.pgn.contains("2. Nf3 Nc6 1/2-1/2"));
        assert!(up.pgn.contains("[Result \"1/2-1/2\"]"));
        assert_eq!(up.accuracy_white, Some(87.5));
        assert_eq!(up.accuracy_black, None);

        // Invalid patch leaves the game unchanged.
        assert!(s
            .update_game(
                g.id,
                &GamePatch {
                    moves: Some(vec!["e2e5".into()]),
                    ..Default::default()
                }
            )
            .is_err());
        assert!(s
            .update_game(
                g.id,
                &GamePatch {
                    review_json: Some("{oops".into()),
                    ..Default::default()
                }
            )
            .is_err());
        assert_eq!(s.get_game(g.id).unwrap().unwrap().moves.len(), 4);

        assert!(s
            .update_game(9999, &GamePatch::default())
            .unwrap()
            .is_none());
        assert!(s.delete_game(g.id).unwrap());
        assert!(!s.delete_game(g.id).unwrap());
        assert!(s.get_game(g.id).unwrap().is_none());
    }

    #[test]
    fn rejects_bad_games() {
        let s = Store::open_in_memory().unwrap();
        let mut g = sample("b", "white", "1-0");
        g.moves = vec!["e2e4".into(), "e2e4".into()];
        assert!(s.create_game(&g).is_err());
        g.moves = vec!["zzz".into()];
        assert!(s.create_game(&g).is_err());
        g.moves = vec![];
        g.start_fen = "not a fen".into();
        assert!(s.create_game(&g).is_err());
        g.start_fen = String::new();
        g.result = "banana".into();
        g.user_color = Some("purple".into());
        let rec = s.create_game(&g).unwrap();
        assert_eq!(rec.result, "*");
        assert_eq!(rec.user_color, None);
    }

    #[test]
    fn list_filters() {
        let s = Store::open_in_memory().unwrap();
        s.create_game(&sample("martin", "white", "1-0")).unwrap();
        s.create_game(&sample("martin", "black", "1-0")).unwrap();
        let d = s
            .create_game(&sample("nelson", "white", "1/2-1/2"))
            .unwrap();
        s.update_game(
            d.id,
            &GamePatch {
                favorite: Some(true),
                ..Default::default()
            },
        )
        .unwrap();
        let q = |f: GameQuery| s.list_games(&f).unwrap().len();
        assert_eq!(q(GameQuery::default()), 3);
        assert_eq!(
            q(GameQuery {
                result: Some("win".into()),
                ..Default::default()
            }),
            1
        );
        assert_eq!(
            q(GameQuery {
                result: Some("loss".into()),
                ..Default::default()
            }),
            1
        );
        assert_eq!(
            q(GameQuery {
                result: Some("1-0".into()),
                ..Default::default()
            }),
            2
        );
        assert_eq!(
            q(GameQuery {
                bot_id: Some("martin".into()),
                ..Default::default()
            }),
            2
        );
        assert_eq!(
            q(GameQuery {
                favorite: Some(true),
                ..Default::default()
            }),
            1
        );
        assert_eq!(
            q(GameQuery {
                search: Some("knight".into()),
                ..Default::default()
            }),
            3
        );
        assert_eq!(
            q(GameQuery {
                search: Some("100%_'\"\\".into()),
                ..Default::default()
            }),
            0
        );
        assert_eq!(
            q(GameQuery {
                limit: Some(2),
                ..Default::default()
            }),
            2
        );
        assert_eq!(
            q(GameQuery {
                limit: Some(2),
                offset: Some(2),
                ..Default::default()
            }),
            1
        );

        let st = s.stats().unwrap();
        assert_eq!(
            (st.games_played, st.games_won, st.games_lost, st.games_drawn),
            (3, 1, 1, 1)
        );
        assert_eq!(st.per_bot[0].bot_id, "martin");
        assert_eq!(st.per_bot[0].played, 2);
        assert_eq!(st.recent_results.len(), 3);
        assert_eq!(st.recent_results[0].outcome, "draw");
        assert!(st.streak_days >= 1);
    }

    #[test]
    fn import_opera_game() {
        let s = Store::open_in_memory().unwrap();
        let games = s.import_pgn(OPERA).unwrap();
        assert_eq!(games.len(), 1);
        let g = &games[0];
        assert_eq!(g.white, "Paul Morphy");
        assert_eq!(g.result, "1-0");
        assert_eq!(g.moves.len(), 33);
        assert_eq!(g.opening_name.as_deref(), Some("Philidor Defense"));
        assert!(g.pgn.contains("[Date \"1858.??.??\"]"));
        assert!(g.pgn.contains("17. Rd8# 1-0"));
        // Export -> re-import roundtrip.
        let all = s.export_pgn(&GameQuery::default()).unwrap();
        let again = s.import_pgn(&all).unwrap();
        assert_eq!(again[0].moves, g.moves);
        // Imported games do not count as the user's games.
        assert_eq!(s.stats().unwrap().games_played, 0);
        assert_eq!(s.stats().unwrap().total_games, 2);
        assert!(s.import_pgn("1. e4 e5 2. Qxf7 *").is_err());
        assert!(s.import_pgn("").is_err());
    }

    #[test]
    fn puzzle_rating_monotonic() {
        let s = Store::open_in_memory().unwrap();
        let p0 = s.get_profile().unwrap();
        assert_eq!(p0.puzzle_rating, 1200.0);
        assert_eq!(p0.puzzle_rd, 350.0);
        let mut last = p0.puzzle_rating;
        for i in 0..10 {
            let r = s
                .record_puzzle_attempt(&format!("p{i}"), 1300, true, 5000)
                .unwrap();
            assert!(r.delta >= 1.0 && r.rating > last, "{r:?}");
            assert_eq!(r.rating, last + r.delta);
            last = r.rating;
        }
        for i in 0..10 {
            let r = s
                .record_puzzle_attempt(&format!("q{i}"), 1300, false, 5000)
                .unwrap();
            assert!(r.delta <= -1.0 && r.rating < last, "{r:?}");
            last = r.rating;
        }
        let p = s.get_profile().unwrap();
        assert_eq!(p.puzzles_solved, 10);
        assert_eq!(p.puzzles_failed, 10);
        assert!(p.puzzle_rd < 350.0);
        assert_eq!(p.puzzle_rating, last);
        assert_eq!(p.streak_days, 1);
        let st = s.stats().unwrap();
        assert_eq!(st.rating_history.len(), 20);
        assert_eq!(st.rating_history.last().unwrap().rating, last);
        assert!(s.record_puzzle_attempt("", 1200, true, 0).is_err());
    }

    #[test]
    fn rush_progress_profile() {
        let s = Store::open_in_memory().unwrap();
        assert_eq!(s.record_rush(12).unwrap(), 12);
        assert_eq!(s.record_rush(7).unwrap(), 12);
        assert_eq!(s.record_rush(20).unwrap(), 20);
        assert_eq!(s.get_profile().unwrap().rush_best, 20);

        s.set_lesson_progress("basics", "l1", true).unwrap();
        s.set_lesson_progress("basics", "l2", false).unwrap();
        s.set_lesson_progress("basics", "l2", true).unwrap();
        assert!(s.set_lesson_progress("", "x", true).is_err());
        let p = s.get_progress().unwrap();
        assert_eq!(p.len(), 2);
        assert!(p.iter().all(|x| x.completed));
        assert_eq!(s.stats().unwrap().lessons_completed, 2);

        let pr = s
            .update_profile(&ProfilePatch {
                name: Some("  Magnus\n ".into()),
                avatar: Some("🦄".into()),
                settings_json: Some("{\"boardTheme\":\"blue\"}".into()),
            })
            .unwrap();
        assert_eq!(pr.name, "Magnus");
        assert_eq!(pr.avatar, "🦄");
        assert!(s
            .update_profile(&ProfilePatch {
                settings_json: Some("[1]".into()),
                ..Default::default()
            })
            .is_err());
        assert!(s
            .update_profile(&ProfilePatch {
                name: Some("   ".into()),
                ..Default::default()
            })
            .is_err());
    }

    #[test]
    fn file_db_reopen_and_migrations() {
        let dir =
            std::env::temp_dir().join(format!("gm-store-test-{}-{}", std::process::id(), line!()));
        let path = dir.join("nested").join("t.db");
        {
            let s = Store::open(&path).unwrap();
            s.create_game(&sample("x", "white", "1-0")).unwrap();
            s.record_puzzle_attempt("p", 1500, true, 1000).unwrap();
        }
        {
            let s = Store::open(&path).unwrap();
            assert_eq!(s.list_games(&GameQuery::default()).unwrap().len(), 1);
            assert!(s.get_profile().unwrap().puzzle_rating > 1200.0);
            let v: i64 = s
                .conn
                .lock()
                .query_row("PRAGMA user_version", [], |r| r.get(0))
                .unwrap();
            assert_eq!(v, MIGRATIONS.len() as i64);
            let mode: String = s
                .conn
                .lock()
                .query_row("PRAGMA journal_mode", [], |r| r.get(0))
                .unwrap();
            assert_eq!(mode.to_ascii_lowercase(), "wal");
        }
        // Legacy scaffold schema (games table without new columns) upgrades cleanly.
        let legacy = dir.join("legacy.db");
        {
            let c = Connection::open(&legacy).unwrap();
            c.execute_batch(
                "CREATE TABLE games (id INTEGER PRIMARY KEY AUTOINCREMENT, white TEXT NOT NULL DEFAULT '', \
                 black TEXT NOT NULL DEFAULT '', result TEXT NOT NULL DEFAULT '*', termination TEXT NOT NULL DEFAULT '', \
                 start_fen TEXT NOT NULL DEFAULT '', moves TEXT NOT NULL DEFAULT '', pgn TEXT NOT NULL DEFAULT '', \
                 bot_id TEXT, user_color TEXT, time_control TEXT, opening_name TEXT, accuracy_white REAL, \
                 accuracy_black REAL, review_json TEXT, notes TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL DEFAULT '', \
                 favorite INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL DEFAULT '');
                 INSERT INTO games (moves) VALUES ('e2e4 e7e5');",
            )
            .unwrap();
        }
        let s = Store::open(&legacy).unwrap();
        assert_eq!(
            s.list_games(&GameQuery::default()).unwrap()[0].move_count,
            2
        );
        drop(s);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn concurrent_clones() {
        let s = Store::open_in_memory().unwrap();
        let handles: Vec<_> = (0..4)
            .map(|i| {
                let s = s.clone();
                std::thread::spawn(move || {
                    for j in 0..10 {
                        s.record_puzzle_attempt(&format!("{i}-{j}"), 1200, j % 2 == 0, 100)
                            .unwrap();
                    }
                })
            })
            .collect();
        for h in handles {
            h.join().unwrap();
        }
        let p = s.get_profile().unwrap();
        assert_eq!(p.puzzles_solved + p.puzzles_failed, 40);
    }
}
