//! Static bot roster: identities, styles and personality chat lines.
//!
//! All chat is kept friendly and encouraging — taunts are playful, never mean.

use gm_content::Lang;

/// Playing style. Affects opening-book choices and move preferences.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Style {
    /// Brand-new player: loves grabbing material and moving the queen early.
    Beginner,
    /// Prefers checks, captures and moves toward the enemy king; gambits in the opening.
    Aggressive,
    /// Prefers quiet improving moves, development, central control, castling.
    Positional,
    /// Prefers solid setups, castling and simplifying trades.
    Defensive,
    /// Prefers openings with known traps and moves that create threats.
    Trappy,
    /// No preference: plays the objectively best moves.
    Universal,
    /// Teaching bot: balanced play plus constant, helpful tips.
    Coach,
}

impl Style {
    pub fn as_str(self) -> &'static str {
        match self {
            Style::Beginner => "beginner",
            Style::Aggressive => "aggressive",
            Style::Positional => "positional",
            Style::Defensive => "defensive",
            Style::Trappy => "trappy",
            Style::Universal => "universal",
            Style::Coach => "coach",
        }
    }
}

/// Id of the adaptive bot whose strength follows the user's results.
pub const ADAPTIVE_ID: &str = "adaptive";
/// Starting level of the adaptive bot before any game has been played.
pub const ADAPTIVE_START_ELO: u16 = 600;

/// A bot's full definition (identity + chat lines per language).
pub struct Persona {
    pub id: &'static str,
    pub name: &'static str,
    pub elo: u16,
    pub avatar: &'static str,
    pub style: Style,
    pub coach: bool,
    pub en: Lines,
    pub es: Lines,
    pub pt: Lines,
    pub fr: Lines,
    pub de: Lines,
}

/// Everything a bot says, in one language.
pub struct Lines {
    pub description: &'static str,
    pub greeting: &'static str,
    /// Bot opens with a named opening. `{opening}` is replaced by its name.
    pub opening: &'static [&'static str],
    /// Bot captures something.
    pub capture: &'static [&'static str],
    /// Opponent just captured one of the bot's pieces.
    pub captured: &'static [&'static str],
    /// Bot is punishing an opponent mistake (wins clear material).
    pub blunder: &'static [&'static str],
    /// Bot gives check.
    pub check: &'static [&'static str],
    /// Bot is clearly winning.
    pub winning: &'static [&'static str],
    /// Bot is clearly losing.
    pub losing: &'static [&'static str],
    /// Bot delivers checkmate.
    pub win: &'static [&'static str],
}

impl Persona {
    /// The bot's text in `lang`.
    pub fn lines(&self, lang: Lang) -> &Lines {
        match lang {
            Lang::En => &self.en,
            Lang::Es => &self.es,
            Lang::Pt => &self.pt,
            Lang::Fr => &self.fr,
            Lang::De => &self.de,
        }
    }

    pub fn category(&self) -> &'static str {
        if self.coach {
            "coach"
        } else {
            match self.elo {
                0..=900 => "beginner",
                901..=1600 => "intermediate",
                1601..=2200 => "advanced",
                _ => "master",
            }
        }
    }
}

/// All bots, weakest first; coaches last.
pub static PERSONAS: &[Persona] = &[
    Persona {
        id: "pawnny",
        name: "Pawnny",
        elo: 250,
        avatar: "🐣",
        style: Style::Beginner,
        coach: false,
        en: Lines {
        description: "Just hatched and just learned how the pieces move. The perfect first opponent.",
        greeting: "Hi hi! I just learned chess yesterday. Be gentle, okay?",
        opening: &["Ooh, I think this one is called the {opening}?"],
        capture: &["Yum, I got one!", "Is that allowed? I took it!", "Chomp!"],
        captured: &["Hey! That was my favorite piece!", "Oh no, where did it go?", "Oopsie..."],
        blunder: &["Wait, was that free? Thank you!", "I found a present!"],
        check: &["Check! Did I say it right?", "Check! Hehe."],
        winning: &["Am I... winning? Wow!"],
        losing: &["You're really good! Can you teach me later?", "My pieces keep disappearing!"],
        win: &["Checkmate?! I WON? I have to tell my mom!"],
        },
        es: Lines {
            description: "Acaba de salir del cascarón y de aprender cómo se mueven las piezas. El rival perfecto para empezar.",
            greeting: "¡Hola, hola! Aprendí ajedrez ayer. Ten paciencia conmigo, ¿vale?",
            opening: &["Uy, ¿creo que esta se llama {opening}?"],
            capture: &["¡Ñam, me comí una!", "¿Eso se puede? ¡Me la llevé!", "¡Chomp!"],
            captured: &["¡Oye! ¡Esa era mi pieza favorita!", "¡Oh, no! ¿Adónde se fue?", "Ups..."],
            blunder: &["Espera, ¿eso era gratis? ¡Gracias!", "¡Encontré un regalito!"],
            check: &["¡Jaque! ¿Lo dije bien?", "¡Jaque! Jiji."],
            winning: &["¿Voy... ganando? ¡Guau!"],
            losing: &["¡Juegas muy bien! ¿Me enseñas luego?", "¡Mis piezas no paran de desaparecer!"],
            win: &["¿¡Jaque mate!? ¿¡GANÉ!? ¡Se lo tengo que contar a mi mamá!"],
        },
        pt: Lines {
            description: "Acabou de sair do ovo e de aprender como as peças se movem. O adversário perfeito para começar.",
            greeting: "Oi, oi! Aprendi xadrez ontem. Vai com calma, tá?",
            opening: &["Uau, acho que essa se chama {opening}?"],
            capture: &["Nhac, peguei uma!", "Pode isso? Peguei!", "Chomp!"],
            captured: &["Ei! Essa era minha peça favorita!", "Ah, não, para onde ela foi?", "Ops..."],
            blunder: &["Espera, isso era de graça? Obrigado!", "Achei um presente!"],
            check: &["Xeque! Falei certo?", "Xeque! Hihi."],
            winning: &["Eu tô... ganhando? Uau!"],
            losing: &["Você joga muito bem! Depois me ensina?", "Minhas peças não param de sumir!"],
            win: &["Xeque-mate?! EU GANHEI? Preciso contar pra minha mãe!"],
        },
        fr: Lines {
            description: "Tout juste sorti de l'œuf, il vient d'apprendre comment bougent les pièces. L'adversaire idéal pour débuter.",
            greeting: "Coucou ! J'ai appris les échecs hier. Sois gentil, d'accord ?",
            opening: &["Oh, je crois que ça s'appelle {opening} ?"],
            capture: &["Miam, j'en ai eu une !", "C'est permis ? Je l'ai prise !", "Croc !"],
            captured: &["Hé ! C'était ma pièce préférée !", "Oh non, elle est passée où ?", "Oups..."],
            blunder: &["Attends, c'était gratuit ? Merci !", "J'ai trouvé un cadeau !"],
            check: &["Échec ! J'ai bien dit ?", "Échec ! Hihi."],
            winning: &["Est-ce que je... gagne ? Waouh !"],
            losing: &["Tu joues super bien ! Tu m'apprendras ?", "Mes pièces n'arrêtent pas de disparaître !"],
            win: &["Échec et mat ?! J'AI GAGNÉ ? Il faut que je le dise à ma maman !"],
        },
        de: Lines {
            description: "Gerade geschlüpft und hat eben erst gelernt, wie die Figuren ziehen. Der perfekte erste Gegner.",
            greeting: "Hallo, hallo! Ich hab gestern erst Schach gelernt. Sei lieb zu mir, ja?",
            opening: &["Oh, ich glaube, das heißt {opening}?"],
            capture: &["Mampf, ich hab eine!", "Darf man das? Ich hab sie genommen!", "Schnapp!"],
            captured: &["Hey! Das war meine Lieblingsfigur!", "Oh nein, wo ist sie hin?", "Hoppla..."],
            blunder: &["Moment, war die umsonst? Danke!", "Ich hab ein Geschenk gefunden!"],
            check: &["Schach! Hab ich das richtig gesagt?", "Schach! Hihi."],
            winning: &["Gewinne ich etwa...? Wow!"],
            losing: &["Du bist richtig gut! Bringst du mir das später bei?", "Meine Figuren verschwinden dauernd!"],
            win: &["Schachmatt?! ICH HAB GEWONNEN? Das muss ich meiner Mama erzählen!"],
        },
    },
    Persona {
        id: "lulu",
        name: "Lulu",
        elo: 450,
        avatar: "🐰",
        style: Style::Aggressive,
        coach: false,
        en: Lines {
        description: "Hops all over the board looking for something to capture. Very excitable.",
        greeting: "Hop hop! Let's see who grabs more pieces!",
        opening: &["The {opening}! I read about it in a carrot magazine."],
        capture: &["Hop, grab, munch!", "Mine now!", "Another one for my basket!"],
        captured: &["Hey, I was using that!", "Aww, you hopped on my piece!"],
        blunder: &["Ooh, that one was just sitting there!", "Free snack!"],
        check: &["Check! Hop hop!", "Your king looks nervous!"],
        winning: &["I'm hopping ahead!"],
        losing: &["You're too fast for me!", "I need more carrots for this..."],
        win: &["Checkmate! Best day ever!"],
        },
        es: Lines {
            description: "Salta por todo el tablero buscando algo que capturar. Se emociona muchísimo.",
            greeting: "¡Hop, hop! ¡A ver quién atrapa más piezas!",
            opening: &["¡{opening}! Lo leí en una revista de zanahorias."],
            capture: &["¡Salto, atrapo y a comer!", "¡Ahora es mía!", "¡Otra más para mi cesta!"],
            captured: &["¡Oye, que la estaba usando!", "¡Ay, saltaste sobre mi pieza!"],
            blunder: &["¡Uy, esa estaba ahí solita!", "¡Merienda gratis!"],
            check: &["¡Jaque! ¡Hop, hop!", "¡Tu rey parece nervioso!"],
            winning: &["¡Voy saltando por delante!"],
            losing: &["¡Eres demasiado rápido para mí!", "Necesito más zanahorias para esto..."],
            win: &["¡Jaque mate! ¡El mejor día de mi vida!"],
        },
        pt: Lines {
            description: "Pula pelo tabuleiro todo procurando algo para capturar. Muito empolgada.",
            greeting: "Hop, hop! Vamos ver quem pega mais peças!",
            opening: &["{opening}! Li sobre isso numa revista de cenouras."],
            capture: &["Pula, pega, come!", "Agora é minha!", "Mais uma para a minha cesta!"],
            captured: &["Ei, eu estava usando essa!", "Ah, você pulou na minha peça!"],
            blunder: &["Uau, essa estava dando sopa!", "Lanchinho grátis!"],
            check: &["Xeque! Hop, hop!", "Seu rei parece nervoso!"],
            winning: &["Estou pulando na frente!"],
            losing: &["Você é rápido demais para mim!", "Preciso de mais cenouras para isso..."],
            win: &["Xeque-mate! Melhor dia da minha vida!"],
        },
        fr: Lines {
            description: "Elle bondit partout sur l'échiquier à la recherche de quelque chose à prendre. Très excitée.",
            greeting: "Hop hop ! Voyons qui attrape le plus de pièces !",
            opening: &["{opening} ! J'ai lu un article dessus dans un magazine de carottes."],
            capture: &["Hop, je prends, je croque !", "À moi maintenant !", "Encore une pour mon panier !"],
            captured: &["Hé, je m'en servais !", "Oh, tu as sauté sur ma pièce !"],
            blunder: &["Oh, celle-là traînait toute seule !", "Goûter gratuit !"],
            check: &["Échec ! Hop hop !", "Ton roi a l'air nerveux !"],
            winning: &["Je bondis en tête !"],
            losing: &["Tu es trop rapide pour moi !", "Il me faudrait plus de carottes..."],
            win: &["Échec et mat ! Le plus beau jour de ma vie !"],
        },
        de: Lines {
            description: "Hoppelt übers ganze Brett und sucht etwas zum Schlagen. Sehr aufgeregt.",
            greeting: "Hopp, hopp! Mal sehen, wer mehr Figuren schnappt!",
            opening: &["{opening}! Darüber hab ich in einer Karottenzeitschrift gelesen."],
            capture: &["Hopp, schnapp, mampf!", "Jetzt gehört sie mir!", "Noch eine für mein Körbchen!"],
            captured: &["Hey, die hab ich noch gebraucht!", "Ach, du bist auf meine Figur gehüpft!"],
            blunder: &["Oh, die stand ja einfach so herum!", "Gratis-Snack!"],
            check: &["Schach! Hopp, hopp!", "Dein König sieht nervös aus!"],
            winning: &["Ich hoppel vorneweg!"],
            losing: &["Du bist zu schnell für mich!", "Dafür brauche ich mehr Karotten..."],
            win: &["Schachmatt! Bester Tag überhaupt!"],
        },
    },
    Persona {
        id: "benny",
        name: "Benny",
        elo: 650,
        avatar: "🐻",
        style: Style::Defensive,
        coach: false,
        en: Lines {
        description: "A cozy bear who likes to hide his king and wait for you to overreach.",
        greeting: "Hello friend. I'll just keep my pieces safe and warm.",
        opening: &["The {opening}. Nice and solid, like a cave."],
        capture: &["A fair trade, I think.", "I'll keep this one safe."],
        captured: &["Grr... okay, that's fair.", "Hmm, I should have guarded that."],
        blunder: &["You left that alone in the woods. I'll take care of it."],
        check: &["Check. Sorry to bother your king."],
        winning: &["Slow and steady, like hibernation."],
        losing: &["Well played. I may need a nap after this."],
        win: &["Checkmate. Good game, friend! Want some honey?"],
        },
        es: Lines {
            description: "Un oso muy tranquilo al que le gusta esconder a su rey y esperar a que te pases de la raya.",
            greeting: "Hola, amigo. Yo solo voy a mantener mis piezas calentitas y a salvo.",
            opening: &["{opening}. Sólida y acogedora, como una cueva."],
            capture: &["Un cambio justo, creo yo.", "Esta la guardo bien guardada."],
            captured: &["Grrr... vale, eso fue justo.", "Mmm, debería haberla defendido."],
            blunder: &["Dejaste eso solito en el bosque. Yo me encargo."],
            check: &["Jaque. Perdón por molestar a tu rey."],
            winning: &["Despacito y con calma, como en la hibernación."],
            losing: &["Bien jugado. Creo que necesitaré una siesta después de esto."],
            win: &["Jaque mate. ¡Buena partida, amigo! ¿Quieres un poco de miel?"],
        },
        pt: Lines {
            description: "Um urso tranquilo que gosta de esconder o rei e esperar você exagerar.",
            greeting: "Olá, amigo. Vou só manter minhas peças quentinhas e seguras.",
            opening: &["{opening}. Uma escolha sólida e aconchegante, como uma caverna."],
            capture: &["Uma troca justa, eu acho.", "Esta eu vou guardar bem guardada."],
            captured: &["Grrr... tá bom, foi justo.", "Hmm, eu devia ter protegido essa."],
            blunder: &["Você deixou isso sozinho na floresta. Eu cuido disso."],
            check: &["Xeque. Desculpe incomodar o seu rei."],
            winning: &["Devagar e sempre, como na hibernação."],
            losing: &["Bem jogado. Acho que vou precisar de uma soneca depois disso."],
            win: &["Xeque-mate. Boa partida, amigo! Quer um pouco de mel?"],
        },
        fr: Lines {
            description: "Un ours tranquille qui aime cacher son roi et attendre que tu en fasses trop.",
            greeting: "Bonjour, l'ami. Je vais juste garder mes pièces bien au chaud et à l'abri.",
            opening: &["{opening}. Un choix solide et douillet, comme une grotte."],
            capture: &["Un échange équitable, je pense.", "Celle-là, je la garde bien au chaud."],
            captured: &["Grrr... d'accord, c'était de bonne guerre.", "Hmm, j'aurais dû la protéger."],
            blunder: &["Tu as laissé ça tout seul dans la forêt. Je m'en occupe."],
            check: &["Échec. Désolé de déranger ton roi."],
            winning: &["Lentement mais sûrement, comme pendant l'hibernation."],
            losing: &["Bien joué. Je vais avoir besoin d'une sieste après ça."],
            win: &["Échec et mat. Belle partie, l'ami ! Un peu de miel ?"],
        },
        de: Lines {
            description: "Ein gemütlicher Bär, der seinen König gern versteckt und abwartet, bis du dich übernimmst.",
            greeting: "Hallo, Freund. Ich halte meine Figuren einfach schön warm und sicher.",
            opening: &["{opening}. Solide und gemütlich, wie eine Höhle."],
            capture: &["Ein fairer Tausch, finde ich.", "Die hier bewahre ich gut auf."],
            captured: &["Grr... na gut, das war fair.", "Hm, die hätte ich decken sollen."],
            blunder: &["Das hast du ganz allein im Wald stehen lassen. Ich kümmere mich drum."],
            check: &["Schach. Entschuldige die Störung, lieber König."],
            winning: &["Langsam und stetig, wie im Winterschlaf."],
            losing: &["Gut gespielt. Danach brauche ich wohl ein Nickerchen."],
            win: &["Schachmatt. Gute Partie, Freund! Magst du etwas Honig?"],
        },
    },
    Persona {
        id: "rosa",
        name: "Rosa",
        elo: 850,
        avatar: "🌹",
        style: Style::Trappy,
        coach: false,
        en: Lines {
        description: "Sweet as a rose... with thorns. Loves setting little traps.",
        greeting: "Hello! Don't mind me, I'm just a harmless flower.",
        opening: &["The {opening}! It has lovely thorns.", "Ah, the {opening}. Watch your step!"],
        capture: &["A thorn for you!", "Snip!"],
        captured: &["Oh! You saw through that one.", "Hmm, I'll grow another trap."],
        blunder: &["Ouch, you stepped on a thorn!", "My trap worked!"],
        check: &["Check! Pricked you!"],
        winning: &["My garden is blooming!"],
        losing: &["You're good at avoiding thorns!"],
        win: &["Checkmate! Every rose has its thorn."],
        },
        es: Lines {
            description: "Dulce como una rosa... con espinas. Le encanta tender pequeñas trampas.",
            greeting: "¡Hola! No me hagas caso, solo soy una flor inofensiva.",
            opening: &["¡{opening}! Tiene unas espinas preciosas.", "Ah, {opening}. ¡Cuidado dónde pisas!"],
            capture: &["¡Una espina para ti!", "¡Zas!"],
            captured: &["¡Oh! Esa no te la creíste.", "Mmm, ya me crecerá otra trampa."],
            blunder: &["¡Ay, pisaste una espina!", "¡Mi trampa funcionó!"],
            check: &["¡Jaque! ¡Te pinché!"],
            winning: &["¡Mi jardín está floreciendo!"],
            losing: &["¡Qué bien esquivas las espinas!"],
            win: &["¡Jaque mate! No hay rosa sin espinas."],
        },
        pt: Lines {
            description: "Doce como uma rosa... com espinhos. Adora armar pequenas armadilhas.",
            greeting: "Olá! Não ligue para mim, sou só uma flor inofensiva.",
            opening: &["{opening}! Tem uns espinhos lindos.", "Ah, {opening}. Cuidado onde pisa!"],
            capture: &["Um espinho para você!", "Zás!"],
            captured: &["Oh! Você não caiu nessa.", "Hmm, vou cultivar outra armadilha."],
            blunder: &["Ai, você pisou num espinho!", "Minha armadilha funcionou!"],
            check: &["Xeque! Te espetei!"],
            winning: &["Meu jardim está florescendo!"],
            losing: &["Você é ótimo em desviar dos espinhos!"],
            win: &["Xeque-mate! Não existe rosa sem espinhos."],
        },
        fr: Lines {
            description: "Douce comme une rose... avec des épines. Adore tendre de petits pièges.",
            greeting: "Bonjour ! Ne fais pas attention à moi, je ne suis qu'une fleur inoffensive.",
            opening: &["{opening} ! Plein de jolies épines.", "Ah, {opening}. Attention où tu mets les pieds !"],
            capture: &["Une épine pour toi !", "Clac !"],
            captured: &["Oh ! Tu ne t'es pas laissé avoir.", "Hmm, je vais faire pousser un autre piège."],
            blunder: &["Aïe, tu as marché sur une épine !", "Mon piège a marché !"],
            check: &["Échec ! Piqué !"],
            winning: &["Mon jardin est en fleurs !"],
            losing: &["Tu évites très bien les épines !"],
            win: &["Échec et mat ! Il n'y a pas de rose sans épines."],
        },
        de: Lines {
            description: "Süß wie eine Rose... mit Dornen. Stellt liebend gern kleine Fallen.",
            greeting: "Hallo! Beachte mich gar nicht, ich bin nur eine harmlose Blume.",
            opening: &["{opening}! Hat wunderschöne Dornen.", "Ah, {opening}. Pass auf, wo du hintrittst!"],
            capture: &["Ein Dorn für dich!", "Schnipp!"],
            captured: &["Oh! Das hast du durchschaut.", "Hm, dann wächst eben eine neue Falle."],
            blunder: &["Autsch, du bist auf einen Dorn getreten!", "Meine Falle hat funktioniert!"],
            check: &["Schach! Gepikst!"],
            winning: &["Mein Garten blüht auf!"],
            losing: &["Du weichst den Dornen echt gut aus!"],
            win: &["Schachmatt! Keine Rose ohne Dornen."],
        },
    },
    Persona {
        id: "tito",
        name: "Tito",
        elo: 1000,
        avatar: "🐢",
        style: Style::Defensive,
        coach: false,
        en: Lines {
        description: "Slow, steady and very hard to crack. Will happily trade down to an endgame.",
        greeting: "Take your time. I always do.",
        opening: &["The {opening}. Steady wins the race."],
        capture: &["Trade accepted.", "One less piece to worry about."],
        captured: &["Hm. I'll pull my head in for a bit.", "Okay, okay. Back into my shell."],
        blunder: &["Steady... steady... and that's a free piece."],
        check: &["Check. Slowly but surely."],
        winning: &["The tortoise is ahead!"],
        losing: &["You hare-like players are always so fast..."],
        win: &["Checkmate. Slow and steady wins the race!"],
        },
        es: Lines {
            description: "Lento, constante y muy difícil de romper. Encantado de cambiar piezas hasta llegar al final.",
            greeting: "Tómate tu tiempo. Yo siempre lo hago.",
            opening: &["{opening}. Paso a paso se llega lejos."],
            capture: &["Cambio aceptado.", "Una pieza menos de la que preocuparse."],
            captured: &["Mmm. Voy a esconder la cabeza un ratito.", "Vale, vale. De vuelta a mi caparazón."],
            blunder: &["Despacio... despacio... y una pieza gratis."],
            check: &["Jaque. Lento pero seguro."],
            winning: &["¡La tortuga va por delante!"],
            losing: &["Ustedes, los jugadores liebre, siempre van tan rápido..."],
            win: &["Jaque mate. ¡Despacio y con constancia se gana la carrera!"],
        },
        pt: Lines {
            description: "Lento, constante e muito difícil de quebrar. Adora trocar peças até chegar ao final.",
            greeting: "Não tenha pressa. Eu nunca tenho.",
            opening: &["{opening}. Devagar se vai ao longe."],
            capture: &["Troca aceita.", "Uma peça a menos para me preocupar."],
            captured: &["Hm. Vou recolher a cabeça um pouquinho.", "Tá bom, tá bom. De volta para o casco."],
            blunder: &["Devagar... devagar... e uma peça de graça."],
            check: &["Xeque. Devagar e sempre."],
            winning: &["A tartaruga está na frente!"],
            losing: &["Vocês, jogadores-lebre, são sempre tão rápidos..."],
            win: &["Xeque-mate. Devagar e sempre se vence a corrida!"],
        },
        fr: Lines {
            description: "Lent, régulier et très difficile à faire craquer. Échange volontiers jusqu'à la finale.",
            greeting: "Prends ton temps. Moi, je prends toujours le mien.",
            opening: &["{opening}. Rien ne sert de courir."],
            capture: &["Échange accepté.", "Une pièce de moins à surveiller."],
            captured: &["Hm. Je rentre la tête un petit moment.", "D'accord, d'accord. Retour dans ma carapace."],
            blunder: &["Doucement... doucement... et voilà une pièce gratuite."],
            check: &["Échec. Lentement mais sûrement."],
            winning: &["La tortue est en tête !"],
            losing: &["Vous, les joueurs-lièvres, vous êtes toujours si rapides..."],
            win: &["Échec et mat. Rien ne sert de courir, il faut partir à point !"],
        },
        de: Lines {
            description: "Langsam, beständig und kaum zu knacken. Tauscht gern bis ins Endspiel ab.",
            greeting: "Lass dir Zeit. Ich mach das immer.",
            opening: &["{opening}. Langsam, aber sicher."],
            capture: &["Tausch angenommen.", "Eine Figur weniger, um die ich mich sorgen muss."],
            captured: &["Hm. Ich zieh mal kurz den Kopf ein.", "Schon gut, schon gut. Zurück in meinen Panzer."],
            blunder: &["Langsam... langsam... und schon ist eine Figur gratis."],
            check: &["Schach. Langsam, aber sicher."],
            winning: &["Die Schildkröte liegt vorn!"],
            losing: &["Ihr Hasen-Spieler seid immer so schnell..."],
            win: &["Schachmatt. Langsam und stetig gewinnt das Rennen!"],
        },
    },
    Persona {
        id: "max",
        name: "Max",
        elo: 1200,
        avatar: "🦊",
        style: Style::Trappy,
        coach: false,
        en: Lines {
        description: "A sly fox who knows every opening trap in the book. Stay alert!",
        greeting: "Hey there! Watch out for my tricks... or don't. Hehe.",
        opening: &["The {opening}? I know all its secrets.", "Ah, the {opening}. My favorite hunting ground."],
        capture: &["Sneaky sneaky!", "Snatched it!"],
        captured: &["Clever! You spotted my plan.", "Hmph, that wasn't part of the plan."],
        blunder: &["Gotcha! Fell right into it!", "The fox strikes again!"],
        check: &["Check! Surprise!", "Check! Bet you didn't see that coming."],
        winning: &["Everything is going according to plan..."],
        losing: &["You're a crafty one too!", "Okay, you outfoxed me."],
        win: &["Checkmate! Never trust a fox. Good game though!"],
        },
        es: Lines {
            description: "Un zorro astuto que se sabe todas las trampas de apertura. ¡No te despistes!",
            greeting: "¡Hola! Cuidado con mis trucos... o no. Jeje.",
            opening: &["¿{opening}? Me sé todos sus secretos.", "Ah, {opening}. Mi coto de caza favorito."],
            capture: &["¡Sigilosito, sigilosito!", "¡La pillé!"],
            captured: &["¡Qué listo! Descubriste mi plan.", "Hmpf, eso no estaba en el plan."],
            blunder: &["¡Te pillé! ¡Caíste de lleno!", "¡El zorro ataca de nuevo!"],
            check: &["¡Jaque! ¡Sorpresa!", "¡Jaque! A que no lo viste venir."],
            winning: &["Todo va según el plan..."],
            losing: &["¡Tú también eres muy astuto!", "Vale, me ganaste en astucia."],
            win: &["¡Jaque mate! Nunca te fíes de un zorro. ¡Buena partida, eso sí!"],
        },
        pt: Lines {
            description: "Uma raposa esperta que conhece todas as armadilhas de abertura. Fique atento!",
            greeting: "E aí! Cuidado com os meus truques... ou não. Hehe.",
            opening: &["{opening}? Conheço todos os segredos dessa linha.", "Ah, {opening}. Meu território de caça favorito."],
            capture: &["De fininho, de fininho!", "Peguei!"],
            captured: &["Esperto! Você descobriu meu plano.", "Hunf, isso não estava no plano."],
            blunder: &["Te peguei! Caiu direitinho!", "A raposa ataca de novo!"],
            check: &["Xeque! Surpresa!", "Xeque! Aposto que você não viu essa."],
            winning: &["Tudo está saindo conforme o plano..."],
            losing: &["Você também é bem esperto!", "Tá bom, você foi mais esperto que eu."],
            win: &["Xeque-mate! Nunca confie numa raposa. Mas foi uma boa partida!"],
        },
        fr: Lines {
            description: "Un renard rusé qui connaît tous les pièges d'ouverture. Reste sur tes gardes !",
            greeting: "Salut ! Méfie-toi de mes ruses... ou pas. Héhé.",
            opening: &["{opening} ? Je connais tous ses secrets.", "Ah, {opening}. Mon terrain de chasse préféré."],
            capture: &["En douce, en douce !", "Chipé !"],
            captured: &["Malin ! Tu as vu clair dans mon jeu.", "Pff, ça ne faisait pas partie du plan."],
            blunder: &["Je t'ai eu ! Tombé en plein dedans !", "Le renard frappe encore !"],
            check: &["Échec ! Surprise !", "Échec ! Je parie que tu ne l'avais pas vu venir."],
            winning: &["Tout se déroule comme prévu..."],
            losing: &["Toi aussi, tu es rusé !", "D'accord, tu as été plus malin que moi."],
            win: &["Échec et mat ! Ne fais jamais confiance à un renard. Belle partie quand même !"],
        },
        de: Lines {
            description: "Ein schlauer Fuchs, der jede Eröffnungsfalle kennt. Bleib wachsam!",
            greeting: "Hey! Pass auf meine Tricks auf... oder lieber nicht. Hehe.",
            opening: &["{opening}? Da kenne ich alle Geheimnisse.", "Ah, {opening}. Mein liebstes Jagdrevier."],
            capture: &["Schleich, schleich!", "Geschnappt!"],
            captured: &["Clever! Du hast meinen Plan durchschaut.", "Pff, das war so nicht geplant."],
            blunder: &["Erwischt! Voll reingetappt!", "Der Fuchs schlägt wieder zu!"],
            check: &["Schach! Überraschung!", "Schach! Wetten, das hast du nicht kommen sehen?"],
            winning: &["Alles läuft nach Plan..."],
            losing: &["Du bist auch ganz schön gerissen!", "Na gut, du hast mich überlistet."],
            win: &["Schachmatt! Trau niemals einem Fuchs. Aber gute Partie!"],
        },
    },
    Persona {
        id: "zara",
        name: "Zara",
        elo: 1400,
        avatar: "🐯",
        style: Style::Aggressive,
        coach: false,
        en: Lines {
        description: "A fierce attacker who throws pawns at your king and loves gambits.",
        greeting: "Rawr! I hope your king has good armor.",
        opening: &["The {opening}! Time to pounce.", "{opening}. Sharp, just how I like it."],
        capture: &["Pounce!", "Claws out!"],
        captured: &["Just a scratch!", "Nice hit. I'll strike back!"],
        blunder: &["Too slow! The tiger strikes!"],
        check: &["Check! Run, little king!", "Check! The hunt is on."],
        winning: &["I can smell victory!"],
        losing: &["You've got sharp claws too!"],
        win: &["Checkmate! What a hunt. Great fight!"],
        },
        es: Lines {
            description: "Una atacante feroz que lanza sus peones contra tu rey y adora los gambitos.",
            greeting: "¡Grrr! Espero que tu rey lleve buena armadura.",
            opening: &["¡{opening}! Hora de saltar sobre la presa.", "{opening}. Afilada, como a mí me gusta."],
            capture: &["¡Zarpazo!", "¡Fuera garras!"],
            captured: &["¡Solo es un rasguño!", "Buen golpe. ¡Te lo devolveré!"],
            blunder: &["¡Demasiado lento! ¡La tigresa ataca!"],
            check: &["¡Jaque! ¡Corre, reyecito!", "¡Jaque! Empieza la cacería."],
            winning: &["¡Ya huelo la victoria!"],
            losing: &["¡Tú también tienes garras afiladas!"],
            win: &["¡Jaque mate! Menuda cacería. ¡Gran lucha!"],
        },
        pt: Lines {
            description: "Uma atacante feroz que lança peões contra o seu rei e adora gambitos.",
            greeting: "Grrr! Espero que o seu rei tenha uma boa armadura.",
            opening: &["{opening}! Hora de dar o bote.", "{opening}. Jogo afiado, do jeito que eu gosto."],
            capture: &["Bote!", "Garras de fora!"],
            captured: &["Foi só um arranhão!", "Belo golpe. Vou revidar!"],
            blunder: &["Lento demais! A tigresa ataca!"],
            check: &["Xeque! Corre, reizinho!", "Xeque! A caçada começou."],
            winning: &["Já sinto o cheiro da vitória!"],
            losing: &["Você também tem garras afiadas!"],
            win: &["Xeque-mate! Que caçada. Grande luta!"],
        },
        fr: Lines {
            description: "Une attaquante féroce qui lance ses pions sur ton roi et adore les gambits.",
            greeting: "Grrr ! J'espère que ton roi a une bonne armure.",
            opening: &["{opening} ! L'heure de bondir.", "{opening}. Du jeu tranchant, comme je l'aime."],
            capture: &["Je bondis !", "Toutes griffes dehors !"],
            captured: &["Juste une égratignure !", "Joli coup. Je vais riposter !"],
            blunder: &["Trop lent ! La tigresse frappe !"],
            check: &["Échec ! Cours, petit roi !", "Échec ! La chasse est ouverte."],
            winning: &["Je sens déjà la victoire !"],
            losing: &["Toi aussi, tu as les griffes acérées !"],
            win: &["Échec et mat ! Quelle chasse. Beau combat !"],
        },
        de: Lines {
            description: "Eine wilde Angreiferin, die ihre Bauern gegen deinen König wirft und Gambits liebt.",
            greeting: "Grrr! Hoffentlich trägt dein König eine gute Rüstung.",
            opening: &["{opening}! Zeit zum Sprung.", "{opening}. Scharf, genau wie ich es mag."],
            capture: &["Sprung!", "Krallen raus!"],
            captured: &["Nur ein Kratzer!", "Guter Treffer. Ich schlage zurück!"],
            blunder: &["Zu langsam! Die Tigerin schlägt zu!"],
            check: &["Schach! Lauf, kleiner König!", "Schach! Die Jagd ist eröffnet."],
            winning: &["Ich rieche schon den Sieg!"],
            losing: &["Du hast auch scharfe Krallen!"],
            win: &["Schachmatt! Was für eine Jagd. Toller Kampf!"],
        },
    },
    Persona {
        id: "oliver",
        name: "Oliver",
        elo: 1600,
        avatar: "🦔",
        style: Style::Positional,
        coach: false,
        en: Lines {
        description: "A thoughtful club player who builds strong positions one small advantage at a time.",
        greeting: "Good to meet you. Let's play a nice, clean game.",
        opening: &["The {opening}, a classic.", "{opening}. Solid foundations."],
        capture: &["That improves my structure.", "Taking that seems right."],
        captured: &["A fair exchange.", "Interesting choice."],
        blunder: &["I believe that piece was undefended.", "That's a tactical oversight, I think."],
        check: &["Check."],
        winning: &["My position is quite comfortable now."],
        losing: &["Your play is very precise. Impressive."],
        win: &["Checkmate. A pleasure to play you!"],
        },
        es: Lines {
            description: "Un jugador de club reflexivo que construye posiciones sólidas sumando pequeñas ventajas.",
            greeting: "Encantado de conocerte. Juguemos una partida bonita y limpia.",
            opening: &["{opening}, todo un clásico.", "{opening}. Unos cimientos sólidos."],
            capture: &["Esto mejora mi estructura.", "Capturar aquí parece lo correcto."],
            captured: &["Un cambio justo.", "Interesante elección."],
            blunder: &["Creo que esa pieza estaba indefensa.", "Me parece que eso fue un descuido táctico."],
            check: &["Jaque."],
            winning: &["Mi posición ya es bastante cómoda."],
            losing: &["Juegas con mucha precisión. Impresionante."],
            win: &["Jaque mate. ¡Ha sido un placer jugar contigo!"],
        },
        pt: Lines {
            description: "Um jogador de clube reflexivo que constrói posições sólidas somando pequenas vantagens.",
            greeting: "Prazer em conhecer você. Vamos jogar uma partida bonita e limpa.",
            opening: &["{opening}, um clássico.", "{opening}. Fundações sólidas."],
            capture: &["Isso melhora a minha estrutura.", "Capturar aqui parece o certo."],
            captured: &["Uma troca justa.", "Escolha interessante."],
            blunder: &["Acho que aquela peça estava indefesa.", "Parece que isso foi um descuido tático."],
            check: &["Xeque."],
            winning: &["Minha posição já está bem confortável."],
            losing: &["Você joga com muita precisão. Impressionante."],
            win: &["Xeque-mate. Foi um prazer jogar com você!"],
        },
        fr: Lines {
            description: "Un joueur de club réfléchi qui bâtit des positions solides, un petit avantage à la fois.",
            greeting: "Enchanté. Jouons une belle partie, bien propre.",
            opening: &["{opening}, un classique.", "{opening}. Des fondations solides."],
            capture: &["Cela améliore ma structure.", "Prendre ici semble juste."],
            captured: &["Un échange équitable.", "Choix intéressant."],
            blunder: &["Je crois que cette pièce n'était pas défendue.", "C'était un oubli tactique, il me semble."],
            check: &["Échec."],
            winning: &["Ma position est maintenant très confortable."],
            losing: &["Ton jeu est très précis. Impressionnant."],
            win: &["Échec et mat. Ce fut un plaisir de jouer contre toi !"],
        },
        de: Lines {
            description: "Ein besonnener Vereinsspieler, der starke Stellungen Vorteil für Vorteil aufbaut.",
            greeting: "Freut mich. Lass uns eine schöne, saubere Partie spielen.",
            opening: &["{opening}, ein Klassiker.", "{opening}. Solide Fundamente."],
            capture: &["Das verbessert meine Struktur.", "Hier zu schlagen scheint richtig."],
            captured: &["Ein fairer Tausch.", "Interessante Wahl."],
            blunder: &["Ich glaube, diese Figur war ungedeckt.", "Das war wohl ein taktisches Versehen."],
            check: &["Schach."],
            winning: &["Meine Stellung ist jetzt recht bequem."],
            losing: &["Du spielst sehr präzise. Beeindruckend."],
            win: &["Schachmatt. Es war mir ein Vergnügen!"],
        },
    },
    Persona {
        id: "nina",
        name: "Nina",
        elo: 1800,
        avatar: "🐺",
        style: Style::Trappy,
        coach: false,
        en: Lines {
        description: "Hunts in the shadows: quiet moves that hide deadly tactical shots.",
        greeting: "Welcome to the forest. Try not to get lost.",
        opening: &["The {opening}. I know where the traps are buried."],
        capture: &["Caught.", "The pack feeds."],
        captured: &["You bite back. Good.", "Noted."],
        blunder: &["You walked right into the den.", "That was the trap."],
        check: &["Check. Awoo!"],
        winning: &["The moon is rising on my side of the board."],
        losing: &["You're a tough hunter."],
        win: &["Checkmate. Well hunted, and good game!"],
        },
        es: Lines {
            description: "Caza entre las sombras: jugadas tranquilas que esconden golpes tácticos letales.",
            greeting: "Bienvenido al bosque. Intenta no perderte.",
            opening: &["{opening}. Sé dónde están enterradas las trampas."],
            capture: &["Atrapada.", "La manada come."],
            captured: &["Muerdes. Bien.", "Anotado."],
            blunder: &["Te metiste de lleno en la guarida.", "Esa era la trampa."],
            check: &["Jaque. ¡Auuu!"],
            winning: &["La luna sale por mi lado del tablero."],
            losing: &["Eres un cazador duro de pelar."],
            win: &["Jaque mate. ¡Buena cacería y buena partida!"],
        },
        pt: Lines {
            description: "Caça nas sombras: lances tranquilos que escondem golpes táticos mortais.",
            greeting: "Bem-vindo à floresta. Tente não se perder.",
            opening: &["{opening}. Sei onde as armadilhas estão enterradas."],
            capture: &["Peguei.", "A matilha se alimenta."],
            captured: &["Você morde de volta. Ótimo.", "Anotado."],
            blunder: &["Você entrou direto no covil.", "Essa era a armadilha."],
            check: &["Xeque. Auuu!"],
            winning: &["A lua está nascendo do meu lado do tabuleiro."],
            losing: &["Você é um caçador difícil de vencer."],
            win: &["Xeque-mate. Boa caçada, e boa partida!"],
        },
        fr: Lines {
            description: "Elle chasse dans l'ombre : des coups calmes qui cachent des coups tactiques mortels.",
            greeting: "Bienvenue dans la forêt. Essaie de ne pas te perdre.",
            opening: &["{opening}. Je sais où les pièges sont enterrés."],
            capture: &["Attrapée.", "La meute se nourrit."],
            captured: &["Tu mords aussi. Bien.", "Noté."],
            blunder: &["Tu es entré tout droit dans la tanière.", "C'était ça, le piège."],
            check: &["Échec. Aouuu !"],
            winning: &["La lune se lève de mon côté de l'échiquier."],
            losing: &["Tu es un chasseur coriace."],
            win: &["Échec et mat. Belle chasse, et belle partie !"],
        },
        de: Lines {
            description: "Jagt im Schatten: ruhige Züge, hinter denen tödliche taktische Schläge lauern.",
            greeting: "Willkommen im Wald. Versuch, dich nicht zu verirren.",
            opening: &["{opening}. Ich weiß, wo die Fallen vergraben sind."],
            capture: &["Gefangen.", "Das Rudel frisst."],
            captured: &["Du beißt zurück. Gut.", "Notiert."],
            blunder: &["Du bist direkt in die Höhle gelaufen.", "Das war die Falle."],
            check: &["Schach. Auuu!"],
            winning: &["Auf meiner Seite des Bretts geht der Mond auf."],
            losing: &["Du bist ein zäher Jäger."],
            win: &["Schachmatt. Gut gejagt, und gute Partie!"],
        },
    },
    Persona {
        id: "viktor",
        name: "Viktor",
        elo: 2000,
        avatar: "🐉",
        style: Style::Aggressive,
        coach: false,
        en: Lines {
        description: "A fire-breathing tactician who sacrifices material to burn down your king's defenses.",
        greeting: "Let's light up the board!",
        opening: &["The {opening}! Pour on the fire.", "{opening}. Let's make it sharp."],
        capture: &["Burned!", "Into the flames!"],
        captured: &["A worthy sacrifice... I hope.", "Bold. I like it."],
        blunder: &["That piece was left in the fire!"],
        check: &["Check! Feel the heat!", "Check!"],
        winning: &["Your castle is on fire!"],
        losing: &["You put out my flames. Impressive!"],
        win: &["Checkmate! What a blaze. Great game!"],
        },
        es: Lines {
            description: "Un táctico que escupe fuego y sacrifica material para reducir a cenizas las defensas de tu rey.",
            greeting: "¡Vamos a incendiar el tablero!",
            opening: &["¡{opening}! A echar leña al fuego.", "{opening}. Pongámosla afilada."],
            capture: &["¡Quemada!", "¡A las llamas!"],
            captured: &["Un sacrificio digno... espero.", "Atrevido. Me gusta."],
            blunder: &["¡Esa pieza se quedó en el fuego!"],
            check: &["¡Jaque! ¡Siente el calor!", "¡Jaque!"],
            winning: &["¡Tu castillo está en llamas!"],
            losing: &["Apagaste mis llamas. ¡Impresionante!"],
            win: &["¡Jaque mate! Menudo incendio. ¡Gran partida!"],
        },
        pt: Lines {
            description: "Um tático que cospe fogo e sacrifica material para reduzir a cinzas as defesas do seu rei.",
            greeting: "Vamos incendiar o tabuleiro!",
            opening: &["{opening}! Mais lenha na fogueira.", "{opening}. Vamos deixar tudo afiado."],
            capture: &["Queimada!", "Para as chamas!"],
            captured: &["Um sacrifício digno... espero.", "Ousado. Gostei."],
            blunder: &["Essa peça ficou no fogo!"],
            check: &["Xeque! Sinta o calor!", "Xeque!"],
            winning: &["Seu castelo está em chamas!"],
            losing: &["Você apagou minhas chamas. Impressionante!"],
            win: &["Xeque-mate! Que incêndio. Grande partida!"],
        },
        fr: Lines {
            description: "Un tacticien qui crache du feu et sacrifie du matériel pour réduire en cendres les défenses de ton roi.",
            greeting: "Mettons le feu à l'échiquier !",
            opening: &["{opening} ! Jetons de l'huile sur le feu.", "{opening}. Rendons ça tranchant."],
            capture: &["Brûlée !", "Dans les flammes !"],
            captured: &["Un sacrifice digne... j'espère.", "Audacieux. J'aime ça."],
            blunder: &["Cette pièce est restée dans le feu !"],
            check: &["Échec ! Sens la chaleur !", "Échec !"],
            winning: &["Ton château est en feu !"],
            losing: &["Tu as éteint mes flammes. Impressionnant !"],
            win: &["Échec et mat ! Quel brasier. Superbe partie !"],
        },
        de: Lines {
            description: "Ein feuerspeiender Taktiker, der Material opfert, um die Verteidigung deines Königs niederzubrennen.",
            greeting: "Lass uns das Brett in Flammen setzen!",
            opening: &["{opening}! Öl ins Feuer.", "{opening}. Machen wir's scharf."],
            capture: &["Verbrannt!", "Ab in die Flammen!"],
            captured: &["Ein würdiges Opfer... hoffe ich.", "Mutig. Gefällt mir."],
            blunder: &["Die Figur stand mitten im Feuer!"],
            check: &["Schach! Spür die Hitze!", "Schach!"],
            winning: &["Deine Burg steht in Flammen!"],
            losing: &["Du hast meine Flammen gelöscht. Beeindruckend!"],
            win: &["Schachmatt! Was für ein Inferno. Tolle Partie!"],
        },
    },
    Persona {
        id: "sofia",
        name: "Sofia",
        elo: 2200,
        avatar: "🦢",
        style: Style::Positional,
        coach: false,
        en: Lines {
        description: "Graceful and precise. Squeezes small advantages into winning endgames.",
        greeting: "Hello. Let's create something beautiful together.",
        opening: &["The {opening}. Elegant choice.", "Ah, the {opening}."],
        capture: &["Simplifying.", "Clean."],
        captured: &["Well calculated.", "Mm, good move."],
        blunder: &["I think that was a slip. I'll take it, gracefully."],
        check: &["Check."],
        winning: &["The endgame will be pleasant for me, I think."],
        losing: &["Beautiful play. I'm impressed."],
        win: &["Checkmate. Thank you for a lovely game!"],
        },
        es: Lines {
            description: "Elegante y precisa. Exprime pequeñas ventajas hasta convertirlas en finales ganados.",
            greeting: "Hola. Creemos juntos algo bonito.",
            opening: &["{opening}. Una elección elegante.", "Ah, {opening}."],
            capture: &["Simplificando.", "Limpio."],
            captured: &["Bien calculado.", "Mmm, buena jugada."],
            blunder: &["Creo que eso fue un desliz. Lo aprovecharé, con elegancia."],
            check: &["Jaque."],
            winning: &["Creo que el final será agradable para mí."],
            losing: &["Un juego precioso. Estoy impresionada."],
            win: &["Jaque mate. ¡Gracias por una partida encantadora!"],
        },
        pt: Lines {
            description: "Elegante e precisa. Espreme pequenas vantagens até transformá-las em finais vencedores.",
            greeting: "Olá. Vamos criar algo bonito juntos.",
            opening: &["{opening}. Uma escolha elegante.", "Ah, {opening}."],
            capture: &["Simplificando.", "Limpo."],
            captured: &["Bem calculado.", "Hmm, bom lance."],
            blunder: &["Acho que isso foi um deslize. Vou aproveitar, com elegância."],
            check: &["Xeque."],
            winning: &["Acho que o final vai ser agradável para mim."],
            losing: &["Um jogo lindo. Estou impressionada."],
            win: &["Xeque-mate. Obrigada pela partida encantadora!"],
        },
        fr: Lines {
            description: "Gracieuse et précise. Elle transforme de petits avantages en finales gagnantes.",
            greeting: "Bonjour. Créons ensemble quelque chose de beau.",
            opening: &["{opening}. Un choix élégant.", "Ah, {opening}."],
            capture: &["Je simplifie.", "Propre."],
            captured: &["Bien calculé.", "Mm, bon coup."],
            blunder: &["Je crois que c'était une inattention. J'en profite, avec grâce."],
            check: &["Échec."],
            winning: &["La finale devrait m'être agréable, je pense."],
            losing: &["Un jeu magnifique. Je suis impressionnée."],
            win: &["Échec et mat. Merci pour cette charmante partie !"],
        },
        de: Lines {
            description: "Anmutig und präzise. Verwandelt kleine Vorteile in gewonnene Endspiele.",
            greeting: "Hallo. Lass uns gemeinsam etwas Schönes erschaffen.",
            opening: &["{opening}. Eine elegante Wahl.", "Ah, {opening}."],
            capture: &["Vereinfachen.", "Sauber."],
            captured: &["Gut berechnet.", "Mm, guter Zug."],
            blunder: &["Ich glaube, das war ein Ausrutscher. Den nutze ich – mit Anmut."],
            check: &["Schach."],
            winning: &["Das Endspiel wird für mich wohl angenehm."],
            losing: &["Wunderschönes Spiel. Ich bin beeindruckt."],
            win: &["Schachmatt. Danke für die schöne Partie!"],
        },
    },
    Persona {
        id: "kai",
        name: "Kai",
        elo: 2450,
        avatar: "⚡",
        style: Style::Aggressive,
        coach: false,
        en: Lines {
        description: "A lightning-fast attacking master. Every move is a threat.",
        greeting: "Ready? This is going to be fast.",
        opening: &["The {opening}. Charging up!", "{opening}, full speed."],
        capture: &["Zap!", "Strike!"],
        captured: &["Quick reflexes!", "Nice shot."],
        blunder: &["Lightning never misses an open target!"],
        check: &["Check! Zzzap!", "Check!"],
        winning: &["Full voltage!"],
        losing: &["You're shocking me! Great play."],
        win: &["Checkmate! Thunder and lightning. GG!"],
        },
        es: Lines {
            description: "Un maestro del ataque rápido como el rayo. Cada jugada es una amenaza.",
            greeting: "¿Listo? Esto va a ir rápido.",
            opening: &["{opening}. ¡Cargando energía!", "{opening}, a toda velocidad."],
            capture: &["¡Zas!", "¡Golpe!"],
            captured: &["¡Qué reflejos!", "Buen disparo."],
            blunder: &["¡El rayo nunca falla un blanco descubierto!"],
            check: &["¡Jaque! ¡Bzzzt!", "¡Jaque!"],
            winning: &["¡A máximo voltaje!"],
            losing: &["¡Me dejas electrizado! Gran juego."],
            win: &["¡Jaque mate! Rayos y truenos. ¡Buena partida!"],
        },
        pt: Lines {
            description: "Um mestre do ataque rápido como um raio. Cada lance é uma ameaça.",
            greeting: "Pronto? Isso vai ser rápido.",
            opening: &["{opening}. Carregando energia!", "{opening}, a toda velocidade."],
            capture: &["Zap!", "Golpe!"],
            captured: &["Que reflexos!", "Belo tiro."],
            blunder: &["O raio nunca erra um alvo desprotegido!"],
            check: &["Xeque! Bzzzt!", "Xeque!"],
            winning: &["Voltagem máxima!"],
            losing: &["Você está me dando choque! Grande jogo."],
            win: &["Xeque-mate! Raios e trovões. Boa partida!"],
        },
        fr: Lines {
            description: "Un maître de l'attaque, rapide comme l'éclair. Chaque coup est une menace.",
            greeting: "Prêt ? Ça va aller vite.",
            opening: &["{opening}. Je me recharge !", "{opening}, à pleine vitesse."],
            capture: &["Zap !", "Frappe !"],
            captured: &["Quels réflexes !", "Joli tir."],
            blunder: &["L'éclair ne rate jamais une cible à découvert !"],
            check: &["Échec ! Bzzzt !", "Échec !"],
            winning: &["Pleine tension !"],
            losing: &["Tu m'électrises ! Superbe jeu."],
            win: &["Échec et mat ! Tonnerre et éclairs. GG !"],
        },
        de: Lines {
            description: "Ein blitzschneller Angriffsmeister. Jeder Zug ist eine Drohung.",
            greeting: "Bereit? Das wird schnell gehen.",
            opening: &["{opening}. Ich lade auf!", "{opening}, volle Geschwindigkeit."],
            capture: &["Zack!", "Treffer!"],
            captured: &["Schnelle Reflexe!", "Guter Schuss."],
            blunder: &["Der Blitz verfehlt nie ein offenes Ziel!"],
            check: &["Schach! Bzzzt!", "Schach!"],
            winning: &["Volle Spannung!"],
            losing: &["Du elektrisierst mich! Tolles Spiel."],
            win: &["Schachmatt! Blitz und Donner. GG!"],
        },
    },
    Persona {
        id: "athena",
        name: "Athena",
        elo: 2700,
        avatar: "🦉",
        style: Style::Positional,
        coach: false,
        en: Lines {
        description: "Wise strategist at grandmaster level. Every piece has a purpose.",
        greeting: "Wisdom is patience. Show me your best chess.",
        opening: &["The {opening}. Its ideas run deep.", "A fine opening: the {opening}."],
        capture: &["As planned.", "Strategy pays off."],
        captured: &["A well-founded decision.", "Good, you understand the position."],
        blunder: &["An inaccuracy, I believe. I will take advantage."],
        check: &["Check."],
        winning: &["The position speaks for itself."],
        losing: &["Remarkable. You have studied well."],
        win: &["Checkmate. You played with courage. Keep learning!"],
        },
        es: Lines {
            description: "Una estratega sabia con nivel de gran maestra. Cada pieza tiene un propósito.",
            greeting: "La sabiduría es paciencia. Muéstrame tu mejor ajedrez.",
            opening: &["{opening}. Sus ideas son profundas.", "Una buena apertura: {opening}."],
            capture: &["Tal como estaba previsto.", "La estrategia da sus frutos."],
            captured: &["Una decisión bien fundada.", "Bien, entiendes la posición."],
            blunder: &["Creo que eso fue una imprecisión. La aprovecharé."],
            check: &["Jaque."],
            winning: &["La posición habla por sí sola."],
            losing: &["Notable. Has estudiado bien."],
            win: &["Jaque mate. Jugaste con valentía. ¡Sigue aprendiendo!"],
        },
        pt: Lines {
            description: "Uma estrategista sábia com nível de grande mestra. Cada peça tem um propósito.",
            greeting: "Sabedoria é paciência. Mostre-me o seu melhor xadrez.",
            opening: &["{opening}. Suas ideias são profundas.", "Uma bela abertura: {opening}."],
            capture: &["Como planejado.", "A estratégia dá frutos."],
            captured: &["Uma decisão bem fundamentada.", "Bom, você entende a posição."],
            blunder: &["Acredito que isso foi uma imprecisão. Vou aproveitar."],
            check: &["Xeque."],
            winning: &["A posição fala por si."],
            losing: &["Notável. Você estudou bem."],
            win: &["Xeque-mate. Você jogou com coragem. Continue aprendendo!"],
        },
        fr: Lines {
            description: "Une stratège avisée au niveau grand maître. Chaque pièce a un rôle.",
            greeting: "La sagesse, c'est la patience. Montre-moi tes meilleurs échecs.",
            opening: &["{opening}. Ses idées sont profondes.", "Une belle ouverture : {opening}."],
            capture: &["Comme prévu.", "La stratégie porte ses fruits."],
            captured: &["Une décision bien fondée.", "Bien, tu comprends la position."],
            blunder: &["Une imprécision, je crois. Je vais en profiter."],
            check: &["Échec."],
            winning: &["La position parle d'elle-même."],
            losing: &["Remarquable. Tu as bien étudié."],
            win: &["Échec et mat. Tu as joué avec courage. Continue d'apprendre !"],
        },
        de: Lines {
            description: "Eine weise Strategin auf Großmeisterniveau. Jede Figur hat eine Aufgabe.",
            greeting: "Weisheit ist Geduld. Zeig mir dein bestes Schach.",
            opening: &["{opening}. Tiefgründige Ideen.", "Eine feine Eröffnung: {opening}."],
            capture: &["Wie geplant.", "Die Strategie zahlt sich aus."],
            captured: &["Eine gut begründete Entscheidung.", "Gut, du verstehst die Stellung."],
            blunder: &["Eine Ungenauigkeit, glaube ich. Die nutze ich aus."],
            check: &["Schach."],
            winning: &["Die Stellung spricht für sich."],
            losing: &["Bemerkenswert. Du hast gut gelernt."],
            win: &["Schachmatt. Du hast mutig gespielt. Lern weiter!"],
        },
    },
    Persona {
        id: "titan",
        name: "Titan",
        elo: 3000,
        avatar: "🤖",
        style: Style::Universal,
        coach: false,
        en: Lines {
        description: "Full-strength engine. No mercy, no mistakes. Can you hold a draw?",
        greeting: "SYSTEM ONLINE. CALCULATING OPTIMAL MOVES.",
        opening: &["OPENING DATABASE: {opening}."],
        capture: &["MATERIAL ACQUIRED.", "TARGET CAPTURED."],
        captured: &["EXCHANGE REGISTERED.", "RECALCULATING."],
        blunder: &["ERROR DETECTED IN OPPONENT PROCESS. EXPLOITING."],
        check: &["CHECK."],
        winning: &["WIN PROBABILITY RISING.", "EVALUATION: FAVORABLE."],
        losing: &["UNEXPECTED. IMPRESSIVE, HUMAN.", "RECALIBRATING... YOU ARE STRONG."],
        win: &["CHECKMATE. GOOD GAME, HUMAN. TRY AGAIN?"],
        },
        es: Lines {
            description: "Motor a plena potencia. Sin piedad y sin errores. ¿Podrás arrancarle unas tablas?",
            greeting: "SISTEMA EN LÍNEA. CALCULANDO JUGADAS ÓPTIMAS.",
            opening: &["BASE DE DATOS DE APERTURAS: {opening}."],
            capture: &["MATERIAL ADQUIRIDO.", "OBJETIVO CAPTURADO."],
            captured: &["CAMBIO REGISTRADO.", "RECALCULANDO."],
            blunder: &["ERROR DETECTADO EN EL PROCESO RIVAL. EXPLOTANDO."],
            check: &["JAQUE."],
            winning: &["PROBABILIDAD DE VICTORIA EN AUMENTO.", "EVALUACIÓN: FAVORABLE."],
            losing: &["INESPERADO. IMPRESIONANTE, HUMANO.", "RECALIBRANDO... ERES FUERTE."],
            win: &["JAQUE MATE. BUENA PARTIDA, HUMANO. ¿OTRA?"],
        },
        pt: Lines {
            description: "Motor em força total. Sem piedade, sem erros. Você consegue arrancar um empate?",
            greeting: "SISTEMA ONLINE. CALCULANDO LANCES ÓTIMOS.",
            opening: &["BANCO DE DADOS DE ABERTURAS: {opening}."],
            capture: &["MATERIAL ADQUIRIDO.", "ALVO CAPTURADO."],
            captured: &["TROCA REGISTRADA.", "RECALCULANDO."],
            blunder: &["ERRO DETECTADO NO PROCESSO ADVERSÁRIO. EXPLORANDO."],
            check: &["XEQUE."],
            winning: &["PROBABILIDADE DE VITÓRIA EM ALTA.", "AVALIAÇÃO: FAVORÁVEL."],
            losing: &["INESPERADO. IMPRESSIONANTE, HUMANO.", "RECALIBRANDO... VOCÊ É FORTE."],
            win: &["XEQUE-MATE. BOA PARTIDA, HUMANO. OUTRA?"],
        },
        fr: Lines {
            description: "Moteur à pleine puissance. Aucune pitié, aucune erreur. Arriveras-tu à arracher la nulle ?",
            greeting: "SYSTÈME EN LIGNE. CALCUL DES COUPS OPTIMAUX.",
            opening: &["BASE DE DONNÉES D'OUVERTURES : {opening}."],
            capture: &["MATÉRIEL ACQUIS.", "CIBLE CAPTURÉE."],
            captured: &["ÉCHANGE ENREGISTRÉ.", "NOUVEAU CALCUL."],
            blunder: &["ERREUR DÉTECTÉE DANS LE PROCESSUS ADVERSE. EXPLOITATION."],
            check: &["ÉCHEC."],
            winning: &["PROBABILITÉ DE VICTOIRE EN HAUSSE.", "ÉVALUATION : FAVORABLE."],
            losing: &["INATTENDU. IMPRESSIONNANT, HUMAIN.", "RECALIBRAGE... TU ES FORT."],
            win: &["ÉCHEC ET MAT. BELLE PARTIE, HUMAIN. ON REJOUE ?"],
        },
        de: Lines {
            description: "Engine mit voller Stärke. Keine Gnade, keine Fehler. Schaffst du ein Remis?",
            greeting: "SYSTEM ONLINE. BERECHNE OPTIMALE ZÜGE.",
            opening: &["ERÖFFNUNGSDATENBANK: {opening}."],
            capture: &["MATERIAL ERWORBEN.", "ZIEL ERFASST."],
            captured: &["TAUSCH REGISTRIERT.", "NEUBERECHNUNG."],
            blunder: &["FEHLER IM GEGNERISCHEN PROZESS ERKANNT. WIRD AUSGENUTZT."],
            check: &["SCHACH."],
            winning: &["GEWINNWAHRSCHEINLICHKEIT STEIGT.", "BEWERTUNG: GÜNSTIG."],
            losing: &["UNERWARTET. BEEINDRUCKEND, MENSCH.", "NEUKALIBRIERUNG... DU BIST STARK."],
            win: &["SCHACHMATT. GUTE PARTIE, MENSCH. NOCH EINMAL?"],
        },
    },
    // ---- adaptive --------------------------------------------------------------------------
    // Sparky's `elo` is only the starting level: the server passes the stored adaptive level
    // (see `choose_move_at`), which moves up after the user wins and down after a loss.
    Persona {
        id: ADAPTIVE_ID,
        name: "Sparky",
        elo: ADAPTIVE_START_ELO,
        avatar: "⚡",
        style: Style::Universal,
        coach: false,
        en: Lines {
        description: "Grows with you! Sparky gets a little stronger every time you win and a little gentler when you lose, so every game is a fair fight.",
        greeting: "Hey there! I'll match your level, so every game is close. Ready?",
        opening: &["The {opening}! I'm learning this one too.", "Ooh, the {opening}. Let's see how it goes!"],
        capture: &["Zap! Got one.", "I'll take that, thanks!"],
        captured: &["Nice capture! You're getting sharper.", "Hey, I was using that!"],
        blunder: &["Oops, that one was loose! Keep an eye on your pieces.", "Free piece? Zap!"],
        check: &["Check! Zzzap!", "Check!"],
        winning: &["I'm ahead, but you can still turn this around!"],
        losing: &["Whoa, you're good! I'll level up for next time."],
        win: &["Checkmate! Good fight. I'll go a bit easier next game."],
        },
        es: Lines {
            description: "¡Crece contigo! Sparky se vuelve un poco más fuerte cada vez que ganas y un poco más suave cuando pierdes, para que cada partida sea pareja.",
            greeting: "¡Hola! Me ajusto a tu nivel, así que cada partida será reñida. ¿Empezamos?",
            opening: &["¡{opening}! Yo también la estoy aprendiendo.", "Uy, {opening}. ¡A ver qué tal sale!"],
            capture: &["¡Zas! Me llevo una.", "¡Me la quedo, gracias!"],
            captured: &["¡Buena captura! Cada vez juegas mejor.", "¡Oye, que la estaba usando!"],
            blunder: &["¡Uy, esa estaba suelta! Vigila tus piezas.", "¿Pieza gratis? ¡Zas!"],
            check: &["¡Jaque! ¡Bzzz!", "¡Jaque!"],
            winning: &["Voy por delante, ¡pero todavía puedes darle la vuelta!"],
            losing: &["¡Guau, qué bien juegas! Subiré de nivel para la próxima."],
            win: &["¡Jaque mate! Buena pelea. En la próxima iré un poco más suave."],
        },
        pt: Lines {
            description: "Cresce com você! O Sparky fica um pouco mais forte cada vez que você ganha e um pouco mais suave quando você perde, para que cada partida seja equilibrada.",
            greeting: "E aí! Eu me ajusto ao seu nível, então cada partida vai ser disputada. Vamos?",
            opening: &["{opening}! Também estou aprendendo essa.", "Uau, {opening}. Vamos ver no que dá!"],
            capture: &["Zap! Peguei uma.", "Vou ficar com essa, obrigado!"],
            captured: &["Boa captura! Você está ficando cada vez melhor.", "Ei, eu estava usando essa!"],
            blunder: &["Opa, essa estava solta! Fique de olho nas suas peças.", "Peça de graça? Zap!"],
            check: &["Xeque! Bzzz!", "Xeque!"],
            winning: &["Estou na frente, mas você ainda pode virar o jogo!"],
            losing: &["Uau, você é bom! Vou subir de nível para a próxima."],
            win: &["Xeque-mate! Boa luta. Na próxima vou pegar um pouco mais leve."],
        },
        fr: Lines {
            description: "Il grandit avec toi ! Sparky devient un peu plus fort chaque fois que tu gagnes et un peu plus doux quand tu perds, pour que chaque partie soit équilibrée.",
            greeting: "Salut ! Je m'adapte à ton niveau, donc chaque partie sera serrée. On y va ?",
            opening: &["{opening} ! Je l'apprends aussi.", "Oh, {opening}. Voyons ce que ça donne !"],
            capture: &["Zap ! J'en ai une.", "Je la prends, merci !"],
            captured: &["Belle prise ! Tu progresses.", "Hé, je m'en servais !"],
            blunder: &["Oups, celle-là n'était pas protégée ! Garde un œil sur tes pièces.", "Une pièce gratuite ? Zap !"],
            check: &["Échec ! Bzzz !", "Échec !"],
            winning: &["J'ai de l'avance, mais tu peux encore renverser la partie !"],
            losing: &["Waouh, tu es fort ! Je vais monter de niveau pour la prochaine fois."],
            win: &["Échec et mat ! Beau combat. Je serai un peu plus doux la prochaine fois."],
        },
        de: Lines {
            description: "Wächst mit dir! Sparky wird jedes Mal etwas stärker, wenn du gewinnst, und etwas sanfter, wenn du verlierst – so ist jede Partie ein fairer Kampf.",
            greeting: "Hey! Ich passe mich deinem Niveau an, also wird jede Partie spannend. Bereit?",
            opening: &["{opening}! Das lerne ich auch gerade.", "Oh, {opening}. Mal sehen, wie's läuft!"],
            capture: &["Zack! Eine erwischt.", "Die nehme ich, danke!"],
            captured: &["Schöner Schlag! Du wirst immer besser.", "Hey, die hab ich noch gebraucht!"],
            blunder: &["Hoppla, die war ungedeckt! Behalte deine Figuren im Blick.", "Gratis-Figur? Zack!"],
            check: &["Schach! Bzzz!", "Schach!"],
            winning: &["Ich liege vorn, aber du kannst das Ruder noch herumreißen!"],
            losing: &["Wow, du bist gut! Fürs nächste Mal lege ich eine Stufe zu."],
            win: &["Schachmatt! Guter Kampf. Nächstes Mal mache ich es dir etwas leichter."],
        },
    },
    // ---- coaches ---------------------------------------------------------------------------
    Persona {
        id: "coach",
        name: "Coach Mia",
        elo: 1000,
        avatar: "🎓",
        style: Style::Coach,
        coach: true,
        en: Lines {
        description: "A friendly coach for beginners. Plays fair and gives you a tip after every move.",
        greeting: "Hi, I'm Mia! I'll play and give you tips as we go. Ask yourself every move: what is my opponent threatening?",
        opening: &["We're in the {opening}. Focus on developing knights and bishops and castling early."],
        capture: &["I captured. Can you recapture, or is something else more important?"],
        captured: &["Good capture! Always check what the opponent leaves undefended."],
        blunder: &["Careful — that piece wasn't protected. Before each move, check every piece is safe."],
        check: &["Check! You can move the king, block the check, or capture the checking piece."],
        winning: &["I'm ahead now, but don't give up. Look for checks, captures and threats!"],
        losing: &["You're playing great! When ahead, trade pieces to make winning easier."],
        win: &["Checkmate! Let's review the game together to learn from it."],
        },
        es: Lines {
            description: "Una entrenadora simpática para principiantes. Juega limpio y te da un consejo después de cada jugada.",
            greeting: "¡Hola, soy Mia! Jugaré y te daré consejos sobre la marcha. En cada jugada pregúntate: ¿qué amenaza mi rival?",
            opening: &["Estamos en {opening}. Céntrate en desarrollar caballos y alfiles y en enrocar pronto."],
            capture: &["He capturado. ¿Puedes recapturar, o hay algo más importante?"],
            captured: &["¡Buena captura! Fíjate siempre en lo que tu rival deja sin defender."],
            blunder: &["Cuidado: esa pieza no estaba protegida. Antes de cada jugada, comprueba que todas tus piezas estén a salvo."],
            check: &["¡Jaque! Puedes mover el rey, tapar el jaque o capturar la pieza que lo da."],
            winning: &["Ahora voy por delante, pero no te rindas. ¡Busca jaques, capturas y amenazas!"],
            losing: &["¡Lo estás haciendo genial! Cuando vas ganando, cambia piezas para que sea más fácil rematar."],
            win: &["¡Jaque mate! Revisemos la partida juntos para aprender de ella."],
        },
        pt: Lines {
            description: "Uma treinadora simpática para iniciantes. Joga limpo e dá uma dica depois de cada lance.",
            greeting: "Oi, eu sou a Mia! Vou jogar e dar dicas pelo caminho. A cada lance, pergunte-se: o que o meu adversário está ameaçando?",
            opening: &["Estamos jogando {opening}. Concentre-se em desenvolver cavalos e bispos e em fazer o roque cedo."],
            capture: &["Eu capturei. Você pode recapturar, ou tem algo mais importante?"],
            captured: &["Boa captura! Sempre repare no que o adversário deixa sem defesa."],
            blunder: &["Cuidado: essa peça não estava protegida. Antes de cada lance, confira se todas as suas peças estão seguras."],
            check: &["Xeque! Você pode mover o rei, bloquear o xeque ou capturar a peça que dá o xeque."],
            winning: &["Agora estou na frente, mas não desista. Procure xeques, capturas e ameaças!"],
            losing: &["Você está jogando muito bem! Quando estiver na frente, troque peças para facilitar a vitória."],
            win: &["Xeque-mate! Vamos revisar a partida juntos para aprender com ela."],
        },
        fr: Lines {
            description: "Une entraîneuse sympathique pour débutants. Elle joue loyalement et te donne un conseil après chaque coup.",
            greeting: "Salut, je suis Mia ! Je vais jouer et te donner des conseils en cours de route. À chaque coup, demande-toi : que menace mon adversaire ?",
            opening: &["On joue {opening}. Concentre-toi sur le développement des cavaliers et des fous, et roque tôt."],
            capture: &["J'ai pris une pièce. Peux-tu reprendre, ou y a-t-il plus important ?"],
            captured: &["Belle prise ! Regarde toujours ce que l'adversaire laisse sans défense."],
            blunder: &["Attention : cette pièce n'était pas protégée. Avant chaque coup, vérifie que toutes tes pièces sont à l'abri."],
            check: &["Échec ! Tu peux bouger le roi, interposer une pièce ou prendre la pièce qui donne échec."],
            winning: &["J'ai l'avantage maintenant, mais n'abandonne pas. Cherche les échecs, les captures et les menaces !"],
            losing: &["Tu joues très bien ! Quand tu as l'avantage, échange des pièces pour gagner plus facilement."],
            win: &["Échec et mat ! Revoyons la partie ensemble pour en tirer des leçons."],
        },
        de: Lines {
            description: "Eine freundliche Trainerin für Einsteiger. Spielt fair und gibt dir nach jedem Zug einen Tipp.",
            greeting: "Hallo, ich bin Mia! Ich spiele mit dir und gebe dir unterwegs Tipps. Frag dich bei jedem Zug: Was droht mein Gegner?",
            opening: &["Wir spielen {opening}. Konzentriere dich darauf, Springer und Läufer zu entwickeln und früh zu rochieren."],
            capture: &["Ich habe geschlagen. Kannst du zurückschlagen, oder ist etwas anderes wichtiger?"],
            captured: &["Guter Schlag! Achte immer darauf, was der Gegner ungedeckt lässt."],
            blunder: &["Vorsicht – diese Figur war nicht gedeckt. Prüfe vor jedem Zug, ob alle deine Figuren sicher stehen."],
            check: &["Schach! Du kannst mit dem König ziehen, dazwischenziehen oder die schachgebende Figur schlagen."],
            winning: &["Ich liege jetzt vorn, aber gib nicht auf. Such nach Schachgeboten, Schlagzügen und Drohungen!"],
            losing: &["Du spielst toll! Wenn du vorn liegst, tausche Figuren, dann gewinnst du leichter."],
            win: &["Schachmatt! Lass uns die Partie gemeinsam durchgehen und daraus lernen."],
        },
    },
    Persona {
        id: "coach-leo",
        name: "Coach Leo",
        elo: 1700,
        avatar: "🧑‍🏫",
        style: Style::Coach,
        coach: true,
        en: Lines {
        description: "An experienced coach for improving players. Explains threats, plans and mistakes.",
        greeting: "Hello! I'm Leo. I'll play solid chess and point out ideas as we go. Let's learn something today.",
        opening: &["This is the {opening}. Think about which pawn breaks fit the structure."],
        capture: &["I took material. Is there a forced recapture, or a stronger in-between move?"],
        captured: &["Nice, you won material. Now consolidate: make sure all your pieces are safe."],
        blunder: &["That one was a tactical oversight. Scan for loose pieces and forcing moves before you commit."],
        check: &["Check! Consider all three defenses: move, block, or capture."],
        winning: &["I have the upper hand. Try to create complications and active counterplay."],
        losing: &["You're winning — convert calmly: trade pieces, push passed pawns, avoid counterplay."],
        win: &["Checkmate. Let's run a Game Review and find the turning point."],
        },
        es: Lines {
            description: "Un entrenador experimentado para jugadores que quieren mejorar. Explica amenazas, planes y errores.",
            greeting: "¡Hola! Soy Leo. Jugaré un ajedrez sólido y te señalaré ideas sobre la marcha. Hoy vamos a aprender algo.",
            opening: &["Esto es {opening}. Piensa qué rupturas de peones encajan con la estructura."],
            capture: &["He ganado material. ¿Hay una recaptura forzada, o una jugada intermedia más fuerte?"],
            captured: &["Bien, ganaste material. Ahora consolida: asegúrate de que todas tus piezas estén a salvo."],
            blunder: &["Eso fue un descuido táctico. Busca piezas sueltas y jugadas forzantes antes de decidirte."],
            check: &["¡Jaque! Considera las tres defensas: mover el rey, tapar o capturar."],
            winning: &["Tengo ventaja. Intenta complicar la partida y buscar contrajuego activo."],
            losing: &["Vas ganando: remata con calma; cambia piezas, avanza tus peones pasados y evita el contrajuego."],
            win: &["Jaque mate. Hagamos una Revisión de la partida y busquemos el momento decisivo."],
        },
        pt: Lines {
            description: "Um treinador experiente para quem quer evoluir. Explica ameaças, planos e erros.",
            greeting: "Olá! Eu sou o Leo. Vou jogar um xadrez sólido e apontar ideias pelo caminho. Vamos aprender algo hoje.",
            opening: &["Abertura: {opening}. Pense em quais rupturas de peões combinam com a estrutura."],
            capture: &["Ganhei material. Existe uma recaptura forçada, ou um lance intermediário mais forte?"],
            captured: &["Boa, você ganhou material. Agora consolide: garanta que todas as suas peças estejam seguras."],
            blunder: &["Isso foi um descuido tático. Procure peças soltas e lances forçantes antes de decidir."],
            check: &["Xeque! Considere as três defesas: mover o rei, bloquear ou capturar."],
            winning: &["Estou com vantagem. Tente complicar a partida e buscar contrajogo ativo."],
            losing: &["Você está ganhando: converta com calma; troque peças, avance seus peões passados e evite contrajogo."],
            win: &["Xeque-mate. Vamos fazer uma Revisão da partida e encontrar o momento decisivo."],
        },
        fr: Lines {
            description: "Un entraîneur expérimenté pour les joueurs qui veulent progresser. Il explique les menaces, les plans et les erreurs.",
            greeting: "Bonjour ! Je suis Leo. Je vais jouer des échecs solides et te signaler des idées en cours de route. Apprenons quelque chose aujourd'hui.",
            opening: &["Ouverture jouée : {opening}. Réfléchis aux poussées de pions qui conviennent à la structure."],
            capture: &["J'ai gagné du matériel. Y a-t-il une reprise forcée, ou un coup intermédiaire plus fort ?"],
            captured: &["Bien, tu as gagné du matériel. Maintenant, consolide : vérifie que toutes tes pièces sont à l'abri."],
            blunder: &["C'était un oubli tactique. Cherche les pièces mal protégées et les coups forcés avant de te décider."],
            check: &["Échec ! Pense aux trois défenses : bouger le roi, interposer ou prendre."],
            winning: &["J'ai le dessus. Essaie de compliquer la partie et de chercher un contre-jeu actif."],
            losing: &["Tu gagnes : convertis calmement ; échange des pièces, pousse tes pions passés et évite le contre-jeu."],
            win: &["Échec et mat. Faisons une Revue de la partie pour trouver le tournant."],
        },
        de: Lines {
            description: "Ein erfahrener Trainer für alle, die besser werden wollen. Erklärt Drohungen, Pläne und Fehler.",
            greeting: "Hallo! Ich bin Leo. Ich spiele solides Schach und zeige dir unterwegs Ideen. Lass uns heute etwas lernen.",
            opening: &["Eröffnung: {opening}. Überlege, welche Bauernhebel zur Struktur passen."],
            capture: &["Ich habe Material gewonnen. Gibt es ein erzwungenes Zurückschlagen oder einen stärkeren Zwischenzug?"],
            captured: &["Gut, du hast Material gewonnen. Jetzt konsolidieren: Sorg dafür, dass alle deine Figuren sicher stehen."],
            blunder: &["Das war ein taktisches Versehen. Such nach losen Figuren und forcierenden Zügen, bevor du dich festlegst."],
            check: &["Schach! Denk an alle drei Verteidigungen: ziehen, dazwischenziehen oder schlagen."],
            winning: &["Ich habe die Oberhand. Versuch, die Partie zu verkomplizieren und aktives Gegenspiel zu suchen."],
            losing: &["Du stehst auf Gewinn – verwerte ruhig: Tausche Figuren, schieb deine Freibauern vor und vermeide Gegenspiel."],
            win: &["Schachmatt. Lass uns eine Partieanalyse machen und den Wendepunkt finden."],
        },
    },
];

/// Find a persona by id.
pub fn find(id: &str) -> Option<&'static Persona> {
    PERSONAS.iter().find(|p| p.id == id)
}
