//! Static bot roster: identities, styles and personality chat lines.
//!
//! All chat is kept friendly and encouraging — taunts are playful, never mean.

/// Playing style. Affects opening-book choices and move preferences.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Style {
    /// Brand-new player: loves grabbing material and moving the queen early.
    Beginner,
    /// Prefers checks, captures and moves toward the enemy king; gambits in the opening.
    Aggressive,
    /// Prefers quiet improving moves, development, central control, castling.
    Positional,
    /// Prefers solid setups, castling and simplifying trades.
    Defensive,
    /// Prefers openings with known traps and moves that create threats.
    Trappy,
    /// No preference: plays the objectively best moves.
    Universal,
    /// Teaching bot: balanced play plus constant, helpful tips.
    Coach,
}

impl Style {
    pub fn as_str(self) -> &'static str {
        match self {
            Style::Beginner => "beginner",
            Style::Aggressive => "aggressive",
            Style::Positional => "positional",
            Style::Defensive => "defensive",
            Style::Trappy => "trappy",
            Style::Universal => "universal",
            Style::Coach => "coach",
        }
    }
}

/// A bot's full definition (identity + chat lines).
pub struct Persona {
    pub id: &'static str,
    pub name: &'static str,
    pub elo: u16,
    pub avatar: &'static str,
    pub style: Style,
    pub coach: bool,
    pub description: &'static str,
    pub greeting: &'static str,
    /// Bot opens with a named opening. `{opening}` is replaced by its name.
    pub opening: &'static [&'static str],
    /// Bot captures something.
    pub capture: &'static [&'static str],
    /// Opponent just captured one of the bot's pieces.
    pub captured: &'static [&'static str],
    /// Bot is punishing an opponent mistake (wins clear material).
    pub blunder: &'static [&'static str],
    /// Bot gives check.
    pub check: &'static [&'static str],
    /// Bot is clearly winning.
    pub winning: &'static [&'static str],
    /// Bot is clearly losing.
    pub losing: &'static [&'static str],
    /// Bot delivers checkmate.
    pub win: &'static [&'static str],
}

impl Persona {
    pub fn category(&self) -> &'static str {
        if self.coach {
            "coach"
        } else {
            match self.elo {
                0..=900 => "beginner",
                901..=1600 => "intermediate",
                1601..=2200 => "advanced",
                _ => "master",
            }
        }
    }
}

/// All bots, weakest first; coaches last.
pub static PERSONAS: &[Persona] = &[
    Persona {
        id: "pawnny",
        name: "Pawnny",
        elo: 250,
        avatar: "🐣",
        style: Style::Beginner,
        coach: false,
        description: "Just hatched and just learned how the pieces move. The perfect first opponent.",
        greeting: "Hi hi! I just learned chess yesterday. Be gentle, okay?",
        opening: &["Ooh, I think this one is called the {opening}?"],
        capture: &["Yum, I got one!", "Is that allowed? I took it!", "Chomp!"],
        captured: &["Hey! That was my favorite piece!", "Oh no, where did it go?", "Oopsie..."],
        blunder: &["Wait, was that free? Thank you!", "I found a present!"],
        check: &["Check! Did I say it right?", "Check! Hehe."],
        winning: &["Am I... winning? Wow!"],
        losing: &["You're really good! Can you teach me later?", "My pieces keep disappearing!"],
        win: &["Checkmate?! I WON? I have to tell my mom!"],
    },
    Persona {
        id: "lulu",
        name: "Lulu",
        elo: 450,
        avatar: "🐰",
        style: Style::Aggressive,
        coach: false,
        description: "Hops all over the board looking for something to capture. Very excitable.",
        greeting: "Hop hop! Let's see who grabs more pieces!",
        opening: &["The {opening}! I read about it in a carrot magazine."],
        capture: &["Hop, grab, munch!", "Mine now!", "Another one for my basket!"],
        captured: &["Hey, I was using that!", "Aww, you hopped on my piece!"],
        blunder: &["Ooh, that one was just sitting there!", "Free snack!"],
        check: &["Check! Hop hop!", "Your king looks nervous!"],
        winning: &["I'm hopping ahead!"],
        losing: &["You're too fast for me!", "I need more carrots for this..."],
        win: &["Checkmate! Best day ever!"],
    },
    Persona {
        id: "benny",
        name: "Benny",
        elo: 650,
        avatar: "🐻",
        style: Style::Defensive,
        coach: false,
        description: "A cozy bear who likes to hide his king and wait for you to overreach.",
        greeting: "Hello friend. I'll just keep my pieces safe and warm.",
        opening: &["The {opening}. Nice and solid, like a cave."],
        capture: &["A fair trade, I think.", "I'll keep this one safe."],
        captured: &["Grr... okay, that's fair.", "Hmm, I should have guarded that."],
        blunder: &["You left that alone in the woods. I'll take care of it."],
        check: &["Check. Sorry to bother your king."],
        winning: &["Slow and steady, like hibernation."],
        losing: &["Well played. I may need a nap after this."],
        win: &["Checkmate. Good game, friend! Want some honey?"],
    },
    Persona {
        id: "rosa",
        name: "Rosa",
        elo: 850,
        avatar: "🌹",
        style: Style::Trappy,
        coach: false,
        description: "Sweet as a rose... with thorns. Loves setting little traps.",
        greeting: "Hello! Don't mind me, I'm just a harmless flower.",
        opening: &["The {opening}! It has lovely thorns.", "Ah, the {opening}. Watch your step!"],
        capture: &["A thorn for you!", "Snip!"],
        captured: &["Oh! You saw through that one.", "Hmm, I'll grow another trap."],
        blunder: &["Ouch, you stepped on a thorn!", "My trap worked!"],
        check: &["Check! Pricked you!"],
        winning: &["My garden is blooming!"],
        losing: &["You're good at avoiding thorns!"],
        win: &["Checkmate! Every rose has its thorn."],
    },
    Persona {
        id: "tito",
        name: "Tito",
        elo: 1000,
        avatar: "🐢",
        style: Style::Defensive,
        coach: false,
        description: "Slow, steady and very hard to crack. Will happily trade down to an endgame.",
        greeting: "Take your time. I always do.",
        opening: &["The {opening}. Steady wins the race."],
        capture: &["Trade accepted.", "One less piece to worry about."],
        captured: &["Hm. I'll pull my head in for a bit.", "Okay, okay. Back into my shell."],
        blunder: &["Steady... steady... and that's a free piece."],
        check: &["Check. Slowly but surely."],
        winning: &["The tortoise is ahead!"],
        losing: &["You hare-like players are always so fast..."],
        win: &["Checkmate. Slow and steady wins the race!"],
    },
    Persona {
        id: "max",
        name: "Max",
        elo: 1200,
        avatar: "🦊",
        style: Style::Trappy,
        coach: false,
        description: "A sly fox who knows every opening trap in the book. Stay alert!",
        greeting: "Hey there! Watch out for my tricks... or don't. Hehe.",
        opening: &["The {opening}? I know all its secrets.", "Ah, the {opening}. My favorite hunting ground."],
        capture: &["Sneaky sneaky!", "Snatched it!"],
        captured: &["Clever! You spotted my plan.", "Hmph, that wasn't part of the plan."],
        blunder: &["Gotcha! Fell right into it!", "The fox strikes again!"],
        check: &["Check! Surprise!", "Check! Bet you didn't see that coming."],
        winning: &["Everything is going according to plan..."],
        losing: &["You're a crafty one too!", "Okay, you outfoxed me."],
        win: &["Checkmate! Never trust a fox. Good game though!"],
    },
    Persona {
        id: "zara",
        name: "Zara",
        elo: 1400,
        avatar: "🐯",
        style: Style::Aggressive,
        coach: false,
        description: "A fierce attacker who throws pawns at your king and loves gambits.",
        greeting: "Rawr! I hope your king has good armor.",
        opening: &["The {opening}! Time to pounce.", "{opening}. Sharp, just how I like it."],
        capture: &["Pounce!", "Claws out!"],
        captured: &["Just a scratch!", "Nice hit. I'll strike back!"],
        blunder: &["Too slow! The tiger strikes!"],
        check: &["Check! Run, little king!", "Check! The hunt is on."],
        winning: &["I can smell victory!"],
        losing: &["You've got sharp claws too!"],
        win: &["Checkmate! What a hunt. Great fight!"],
    },
    Persona {
        id: "oliver",
        name: "Oliver",
        elo: 1600,
        avatar: "🦔",
        style: Style::Positional,
        coach: false,
        description: "A thoughtful club player who builds strong positions one small advantage at a time.",
        greeting: "Good to meet you. Let's play a nice, clean game.",
        opening: &["The {opening}, a classic.", "{opening}. Solid foundations."],
        capture: &["That improves my structure.", "Taking that seems right."],
        captured: &["A fair exchange.", "Interesting choice."],
        blunder: &["I believe that piece was undefended.", "That's a tactical oversight, I think."],
        check: &["Check."],
        winning: &["My position is quite comfortable now."],
        losing: &["Your play is very precise. Impressive."],
        win: &["Checkmate. A pleasure to play you!"],
    },
    Persona {
        id: "nina",
        name: "Nina",
        elo: 1800,
        avatar: "🐺",
        style: Style::Trappy,
        coach: false,
        description: "Hunts in the shadows: quiet moves that hide deadly tactical shots.",
        greeting: "Welcome to the forest. Try not to get lost.",
        opening: &["The {opening}. I know where the traps are buried."],
        capture: &["Caught.", "The pack feeds."],
        captured: &["You bite back. Good.", "Noted."],
        blunder: &["You walked right into the den.", "That was the trap."],
        check: &["Check. Awoo!"],
        winning: &["The moon is rising on my side of the board."],
        losing: &["You're a tough hunter."],
        win: &["Checkmate. Well hunted, and good game!"],
    },
    Persona {
        id: "viktor",
        name: "Viktor",
        elo: 2000,
        avatar: "🐉",
        style: Style::Aggressive,
        coach: false,
        description: "A fire-breathing tactician who sacrifices material to burn down your king's defenses.",
        greeting: "Let's light up the board!",
        opening: &["The {opening}! Pour on the fire.", "{opening}. Let's make it sharp."],
        capture: &["Burned!", "Into the flames!"],
        captured: &["A worthy sacrifice... I hope.", "Bold. I like it."],
        blunder: &["That piece was left in the fire!"],
        check: &["Check! Feel the heat!", "Check!"],
        winning: &["Your castle is on fire!"],
        losing: &["You put out my flames. Impressive!"],
        win: &["Checkmate! What a blaze. Great game!"],
    },
    Persona {
        id: "sofia",
        name: "Sofia",
        elo: 2200,
        avatar: "🦢",
        style: Style::Positional,
        coach: false,
        description: "Graceful and precise. Squeezes small advantages into winning endgames.",
        greeting: "Hello. Let's create something beautiful together.",
        opening: &["The {opening}. Elegant choice.", "Ah, the {opening}."],
        capture: &["Simplifying.", "Clean."],
        captured: &["Well calculated.", "Mm, good move."],
        blunder: &["I think that was a slip. I'll take it, gracefully."],
        check: &["Check."],
        winning: &["The endgame will be pleasant for me, I think."],
        losing: &["Beautiful play. I'm impressed."],
        win: &["Checkmate. Thank you for a lovely game!"],
    },
    Persona {
        id: "kai",
        name: "Kai",
        elo: 2450,
        avatar: "⚡",
        style: Style::Aggressive,
        coach: false,
        description: "A lightning-fast attacking master. Every move is a threat.",
        greeting: "Ready? This is going to be fast.",
        opening: &["The {opening}. Charging up!", "{opening}, full speed."],
        capture: &["Zap!", "Strike!"],
        captured: &["Quick reflexes!", "Nice shot."],
        blunder: &["Lightning never misses an open target!"],
        check: &["Check! Zzzap!", "Check!"],
        winning: &["Full voltage!"],
        losing: &["You're shocking me! Great play."],
        win: &["Checkmate! Thunder and lightning. GG!"],
    },
    Persona {
        id: "athena",
        name: "Athena",
        elo: 2700,
        avatar: "🦉",
        style: Style::Positional,
        coach: false,
        description: "Wise strategist at grandmaster level. Every piece has a purpose.",
        greeting: "Wisdom is patience. Show me your best chess.",
        opening: &["The {opening}. Its ideas run deep.", "A fine opening: the {opening}."],
        capture: &["As planned.", "Strategy pays off."],
        captured: &["A well-founded decision.", "Good, you understand the position."],
        blunder: &["An inaccuracy, I believe. I will take advantage."],
        check: &["Check."],
        winning: &["The position speaks for itself."],
        losing: &["Remarkable. You have studied well."],
        win: &["Checkmate. You played with courage. Keep learning!"],
    },
    Persona {
        id: "titan",
        name: "Titan",
        elo: 3000,
        avatar: "🤖",
        style: Style::Universal,
        coach: false,
        description: "Full-strength engine. No mercy, no mistakes. Can you hold a draw?",
        greeting: "SYSTEM ONLINE. CALCULATING OPTIMAL MOVES.",
        opening: &["OPENING DATABASE: {opening}."],
        capture: &["MATERIAL ACQUIRED.", "TARGET CAPTURED."],
        captured: &["EXCHANGE REGISTERED.", "RECALCULATING."],
        blunder: &["ERROR DETECTED IN OPPONENT PROCESS. EXPLOITING."],
        check: &["CHECK."],
        winning: &["WIN PROBABILITY RISING.", "EVALUATION: FAVORABLE."],
        losing: &["UNEXPECTED. IMPRESSIVE, HUMAN.", "RECALIBRATING... YOU ARE STRONG."],
        win: &["CHECKMATE. GOOD GAME, HUMAN. TRY AGAIN?"],
    },
    // ---- coaches ---------------------------------------------------------------------------
    Persona {
        id: "coach",
        name: "Coach Mia",
        elo: 1000,
        avatar: "🎓",
        style: Style::Coach,
        coach: true,
        description: "A friendly coach for beginners. Plays fair and gives you a tip after every move.",
        greeting: "Hi, I'm Mia! I'll play and give you tips as we go. Ask yourself every move: what is my opponent threatening?",
        opening: &["We're in the {opening}. Focus on developing knights and bishops and castling early."],
        capture: &["I captured. Can you recapture, or is something else more important?"],
        captured: &["Good capture! Always check what the opponent leaves undefended."],
        blunder: &["Careful — that piece wasn't protected. Before each move, check every piece is safe."],
        check: &["Check! You can move the king, block the check, or capture the checking piece."],
        winning: &["I'm ahead now, but don't give up. Look for checks, captures and threats!"],
        losing: &["You're playing great! When ahead, trade pieces to make winning easier."],
        win: &["Checkmate! Let's review the game together to learn from it."],
    },
    Persona {
        id: "coach-leo",
        name: "Coach Leo",
        elo: 1700,
        avatar: "🧑‍🏫",
        style: Style::Coach,
        coach: true,
        description: "An experienced coach for improving players. Explains threats, plans and mistakes.",
        greeting: "Hello! I'm Leo. I'll play solid chess and point out ideas as we go. Let's learn something today.",
        opening: &["This is the {opening}. Think about which pawn breaks fit the structure."],
        capture: &["I took material. Is there a forced recapture, or a stronger in-between move?"],
        captured: &["Nice, you won material. Now consolidate: make sure all your pieces are safe."],
        blunder: &["That one was a tactical oversight. Scan for loose pieces and forcing moves before you commit."],
        check: &["Check! Consider all three defenses: move, block, or capture."],
        winning: &["I have the upper hand. Try to create complications and active counterplay."],
        losing: &["You're winning — convert calmly: trade pieces, push passed pawns, avoid counterplay."],
        win: &["Checkmate. Let's run a Game Review and find the turning point."],
    },
];

/// Find a persona by id.
pub fn find(id: &str) -> Option<&'static Persona> {
    PERSONAS.iter().find(|p| p.id == id)
}
